
import com.azure.resourcemanager.managednetworkfabric.models.AclType;
import com.azure.resourcemanager.managednetworkfabric.models.CommunityActionTypes;
import com.azure.resourcemanager.managednetworkfabric.models.ConfigurationType;
import com.azure.resourcemanager.managednetworkfabric.models.ControlPlanAclIpMatchCondition;
import com.azure.resourcemanager.managednetworkfabric.models.ControlPlaneAclAction;
import com.azure.resourcemanager.managednetworkfabric.models.ControlPlaneAclActionType;
import com.azure.resourcemanager.managednetworkfabric.models.ControlPlaneAclMatchCondition;
import com.azure.resourcemanager.managednetworkfabric.models.ControlPlaneAclMatchConfigurationProperties;
import com.azure.resourcemanager.managednetworkfabric.models.ControlPlaneAclPortCondition;
import com.azure.resourcemanager.managednetworkfabric.models.ControlPlaneAclPortMatchCondition;
import com.azure.resourcemanager.managednetworkfabric.models.ControlPlaneAclPortMatchType;
import com.azure.resourcemanager.managednetworkfabric.models.ControlPlaneAclProperties;
import com.azure.resourcemanager.managednetworkfabric.models.ControlPlaneAclTtlMatchCondition;
import com.azure.resourcemanager.managednetworkfabric.models.ControlPlaneAclTtlMatchType;
import com.azure.resourcemanager.managednetworkfabric.models.DeviceRole;
import com.azure.resourcemanager.managednetworkfabric.models.IcmpConfigurationProperties;
import com.azure.resourcemanager.managednetworkfabric.models.IpAddressType;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

/**
 * Samples for AccessControlLists Create.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-07-15/AccessControlLists_Create_ControlPlaneAcl.json
     */
    /**
     * Sample code: AccessControlLists_Create_MaximumSet_Gen - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to ManagedNetworkFabricManager.
     */
    public static void accessControlListsCreateMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.managednetworkfabric.ManagedNetworkFabricManager manager) {
        manager.accessControlLists().define("example-acl").withRegion("eastus")
            .withExistingResourceGroup("example-resource-group").withConfigurationType(ConfigurationType.INLINE)
            .withTags(mapOf("key5032", "fakeTokenPlaceholder")).withAnnotation("annotation")
            .withAclsUrl("https://microsoft.com/a").withDefaultAction(CommunityActionTypes.PERMIT)
            .withAclType(AclType.CP).withDeviceRole(DeviceRole.CE)
            .withControlPlaneAclConfiguration(Arrays.asList(new ControlPlaneAclProperties()
                .withIpAddressType(IpAddressType.IPV4)
                .withMatchConfigurations(Arrays.asList(new ControlPlaneAclMatchConfigurationProperties()
                    .withMatchConfigurationName("example-match-config").withSequenceNumber(3779271459L)
                    .withMatchCondition(new ControlPlaneAclMatchCondition().withProtocolTypes("tcp")
                        .withIpCondition(new ControlPlanAclIpMatchCondition().withSourceIpPrefix("10.0.0.0/24")
                            .withDestinationIpPrefix("10.0.0.0/24"))
                        .withTtlMatchCondition(new ControlPlaneAclTtlMatchCondition().withTtlValue("1")
                            .withTtlMatchType(ControlPlaneAclTtlMatchType.EQUALS))
                        .withPortCondition(new ControlPlaneAclPortMatchCondition()
                            .withSourcePorts(new ControlPlaneAclPortCondition().withPorts(Arrays.asList("100"))
                                .withPortMatchType(ControlPlaneAclPortMatchType.EQUALS))
                            .withDestinationPorts(new ControlPlaneAclPortCondition().withPorts(Arrays.asList("200"))
                                .withPortMatchType(ControlPlaneAclPortMatchType.EQUALS)))
                        .withFlags(Arrays.asList("established"))
                        .withIcmpConfiguration(new IcmpConfigurationProperties().withIcmpTypes(Arrays.asList("icmp"))))
                    .withAction(new ControlPlaneAclAction().withType(ControlPlaneAclActionType.fromString("Drop"))
                        .withRemarkComment("remark"))))))
            .create();
    }

    // Use "Map.of" if available
    @SuppressWarnings("unchecked")
    private static <T> Map<String, T> mapOf(Object... inputs) {
        Map<String, T> map = new HashMap<>();
        for (int i = 0; i < inputs.length; i += 2) {
            String key = (String) inputs[i];
            T value = (T) inputs[i + 1];
            map.put(key, value);
        }
        return map;
    }
}
