
/**
 * Samples for NetworkBootstrapDevices ResyncPasswords.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-07-15/NetworkBootstrapDevices_ResyncPasswords.json
     */
    /**
     * Sample code: Resync the latest passwords to the Network Bootstrap Device. - generated by [MaximumSet] rule -
     * generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to ManagedNetworkFabricManager.
     */
    public static void
        resyncTheLatestPasswordsToTheNetworkBootstrapDeviceGeneratedByMaximumSetRuleGeneratedByMaximumSetRule(
            com.azure.resourcemanager.managednetworkfabric.ManagedNetworkFabricManager manager) {
        manager.networkBootstrapDevices().resyncPasswords("example-rg", "example-device",
            com.azure.core.util.Context.NONE);
    }
}
