
import com.azure.resourcemanager.managednetworkfabric.models.EnableDisableState;
import com.azure.resourcemanager.managednetworkfabric.models.UpdateAdministrativeState;
import java.util.Arrays;

/**
 * Samples for NetworkBootstrapInterfaces UpdateAdministrativeState.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-07-15/NetworkBootstrapInterfaces_UpdateAdministrativeState.json
     */
    /**
     * Sample code: NetworkBootstrapInterfaces_UpdateAdministrativeState_MaximumSet - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to ManagedNetworkFabricManager.
     */
    public static void networkBootstrapInterfacesUpdateAdministrativeStateMaximumSetGeneratedByMaximumSetRule(
        com.azure.resourcemanager.managednetworkfabric.ManagedNetworkFabricManager manager) {
        manager.networkBootstrapInterfaces().updateAdministrativeState("example-rg", "example-device",
            "example-interface",
            new UpdateAdministrativeState().withResourceIds(Arrays.asList("")).withState(EnableDisableState.ENABLE),
            com.azure.core.util.Context.NONE);
    }
}
