
import com.azure.resourcemanager.managednetworkfabric.models.NetworkBootstrapInterface;

/**
 * Samples for NetworkBootstrapInterfaces Update.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-07-15/NetworkBootstrapInterfaces_Update.json
     */
    /**
     * Sample code: NetworkBootstrapInterfaces_Update_MaximumSet - generated by [MaximumSet] rule - generated by
     * [MaximumSet] rule.
     * 
     * @param manager Entry point to ManagedNetworkFabricManager.
     */
    public static void networkBootstrapInterfacesUpdateMaximumSetGeneratedByMaximumSetRuleGeneratedByMaximumSetRule(
        com.azure.resourcemanager.managednetworkfabric.ManagedNetworkFabricManager manager) {
        NetworkBootstrapInterface resource = manager.networkBootstrapInterfaces()
            .getWithResponse("example-rg", "example-device", "example-interface", com.azure.core.util.Context.NONE)
            .getValue();
        resource.update().withSerialNumber("Vendor;Model;HardwareRevisionId;SerialNumber").withAnnotation("annotation")
            .apply();
    }
}
