
/**
 * Samples for NetworkBootstrapInterfaces ListByNetworkBootstrapDevice.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-07-15/NetworkBootstrapInterfaces_ListByNetworkBootstrapDevice.json
     */
    /**
     * Sample code: NetworkBootstrapInterfaces_ListByNetworkBootstrapDevice_MaximumSet - generated by [MaximumSet] rule
     * - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to ManagedNetworkFabricManager.
     */
    public static void
        networkBootstrapInterfacesListByNetworkBootstrapDeviceMaximumSetGeneratedByMaximumSetRuleGeneratedByMaximumSetRule(
            com.azure.resourcemanager.managednetworkfabric.ManagedNetworkFabricManager manager) {
        manager.networkBootstrapInterfaces().listByNetworkBootstrapDevice("example-rg", "example-device",
            com.azure.core.util.Context.NONE);
    }
}
