
/**
 * Samples for NetworkBootstrapDevices Reboot.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-07-15/NetworkBootstrapDevices_Reboot.json
     */
    /**
     * Sample code: NetworkBootstrapDevices_Reboot_MaximumSet - generated by [MaximumSet] rule - generated by
     * [MaximumSet] rule.
     * 
     * @param manager Entry point to ManagedNetworkFabricManager.
     */
    public static void networkBootstrapDevicesRebootMaximumSetGeneratedByMaximumSetRuleGeneratedByMaximumSetRule(
        com.azure.resourcemanager.managednetworkfabric.ManagedNetworkFabricManager manager) {
        manager.networkBootstrapDevices().reboot("example-rg", "example-device", com.azure.core.util.Context.NONE);
    }
}
