
/**
 * Samples for NetworkBootstrapDevices RefreshConfiguration.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-07-15/NetworkBootstrapDevices_RefreshConfiguration.json
     */
    /**
     * Sample code: NetworkBootstrapDevices_RefreshConfiguration_MaximumSet - generated by [MaximumSet] rule - generated
     * by [MaximumSet] rule.
     * 
     * @param manager Entry point to ManagedNetworkFabricManager.
     */
    public static void
        networkBootstrapDevicesRefreshConfigurationMaximumSetGeneratedByMaximumSetRuleGeneratedByMaximumSetRule(
            com.azure.resourcemanager.managednetworkfabric.ManagedNetworkFabricManager manager) {
        manager.networkBootstrapDevices().refreshConfiguration("example-rg", "example-device",
            com.azure.core.util.Context.NONE);
    }
}
