
/**
 * Samples for NetworkBootstrapInterfaces Delete.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-07-15/NetworkBootstrapInterfaces_Delete.json
     */
    /**
     * Sample code: NetworkBootstrapInterfaces_Delete_MaximumSet - generated by [MaximumSet] rule - generated by
     * [MaximumSet] rule.
     * 
     * @param manager Entry point to ManagedNetworkFabricManager.
     */
    public static void networkBootstrapInterfacesDeleteMaximumSetGeneratedByMaximumSetRuleGeneratedByMaximumSetRule(
        com.azure.resourcemanager.managednetworkfabric.ManagedNetworkFabricManager manager) {
        manager.networkBootstrapInterfaces().delete("example-rg", "example-device", "example-interface",
            com.azure.core.util.Context.NONE);
    }
}
