
/**
 * Samples for NetworkBootstrapDevices Delete.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-07-15/NetworkBootstrapDevices_Delete.json
     */
    /**
     * Sample code: NetworkBootstrapDevices_Delete_MaximumSet - generated by [MaximumSet] rule - generated by
     * [MaximumSet] rule.
     * 
     * @param manager Entry point to ManagedNetworkFabricManager.
     */
    public static void networkBootstrapDevicesDeleteMaximumSetGeneratedByMaximumSetRuleGeneratedByMaximumSetRule(
        com.azure.resourcemanager.managednetworkfabric.ManagedNetworkFabricManager manager) {
        manager.networkBootstrapDevices().delete("example-rg", "example-device", com.azure.core.util.Context.NONE);
    }
}
