
import com.azure.core.util.Context;
import com.azure.resourcemanager.sql.models.SecurityAlertPolicyNameAutoGenerated;

/** Samples for ManagedServerSecurityAlertPolicies Get. */
public final class Main {
    /*
     * x-ms-original-file:
     * specification/sql/resource-manager/Microsoft.Sql/stable/2021-11-01/examples/ManagedServerSecurityAlertGet.json
     */
    /**
     * Sample code: Get a managed server's threat detection policy.
     *
     * @param azure The entry point for accessing resource management APIs in Azure.
     */
    public static void getAManagedServerSThreatDetectionPolicy(com.azure.resourcemanager.AzureResourceManager azure) {
        azure.sqlServers().manager().serviceClient().getManagedServerSecurityAlertPolicies().getWithResponse(
            "securityalert-4799", "securityalert-6440", SecurityAlertPolicyNameAutoGenerated.DEFAULT, Context.NONE);
    }
}
