
import com.azure.core.util.Context;
import com.azure.resourcemanager.sql.fluent.models.ServerSecurityAlertPolicyInner;
import com.azure.resourcemanager.sql.models.SecurityAlertPolicyNameAutoGenerated;
import com.azure.resourcemanager.sql.models.SecurityAlertPolicyState;

/** Samples for ServerSecurityAlertPolicies CreateOrUpdate. */
public final class Main {
    /*
     * x-ms-original-file:
     * specification/sql/resource-manager/Microsoft.Sql/stable/2021-11-01/examples/ServerSecurityAlertsCreateMin.json
     */
    /**
     * Sample code: Update a server's threat detection policy with minimal parameters.
     *
     * @param azure The entry point for accessing resource management APIs in Azure.
     */
    public static void
        updateAServerSThreatDetectionPolicyWithMinimalParameters(com.azure.resourcemanager.AzureResourceManager azure) {
        azure.sqlServers().manager().serviceClient().getServerSecurityAlertPolicies().createOrUpdate(
            "securityalert-4799", "securityalert-6440", SecurityAlertPolicyNameAutoGenerated.DEFAULT,
            new ServerSecurityAlertPolicyInner().withState(SecurityAlertPolicyState.ENABLED), Context.NONE);
    }
}
