
/**
 * Samples for Operations List.
 */
public final class Main {
    /*
     * x-ms-original-file: 2024-02-01/Operations_List_MaximumSet_Gen.json
     */
    /**
     * Sample code: Operations_List_MaximumSet_Gen - generated by [MaximumSet] rule - generated by [MaximumSet] rule -
     * generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to LambdaTestHyperExecuteManager.
     */
    public static void
        operationsListMaximumSetGenGeneratedByMaximumSetRuleGeneratedByMaximumSetRuleGeneratedByMaximumSetRule(
            com.azure.resourcemanager.lambdatesthyperexecute.LambdaTestHyperExecuteManager manager) {
        manager.operations().list(com.azure.core.util.Context.NONE);
    }
}
