
/**
 * Samples for Organizations ListByResourceGroup.
 */
public final class Main {
    /*
     * x-ms-original-file: 2024-02-01/Organizations_ListByResourceGroup_MaximumSet_Gen.json
     */
    /**
     * Sample code: Organizations_ListByResourceGroup_MaximumSet_Gen - generated by [MaximumSet] rule - generated by
     * [MaximumSet] rule - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to LambdaTestHyperExecuteManager.
     */
    public static void
        organizationsListByResourceGroupMaximumSetGenGeneratedByMaximumSetRuleGeneratedByMaximumSetRuleGeneratedByMaximumSetRule(
            com.azure.resourcemanager.lambdatesthyperexecute.LambdaTestHyperExecuteManager manager) {
        manager.organizations().listByResourceGroup("rgopenapi", com.azure.core.util.Context.NONE);
    }
}
