
/**
 * Samples for Fleets GetByResourceGroup.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-04-01-preview/Fleets_Get_MaximumSet_Gen.json
     */
    /**
     * Sample code: Gets a Fleet resource. - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to ContainerServiceFleetManager.
     */
    public static void getsAFleetResourceGeneratedByMaximumSetRule(
        com.azure.resourcemanager.containerservicefleet.ContainerServiceFleetManager manager) {
        manager.fleets().getByResourceGroupWithResponse("rgfleets", "fleet1", com.azure.core.util.Context.NONE);
    }
}
