
/**
 * Samples for FleetUpdateStrategies Delete.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-04-01-preview/FleetUpdateStrategies_Delete_MaximumSet_Gen.json
     */
    /**
     * Sample code: Delete a FleetUpdateStrategy resource. - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to ContainerServiceFleetManager.
     */
    public static void deleteAFleetUpdateStrategyResourceGeneratedByMaximumSetRule(
        com.azure.resourcemanager.containerservicefleet.ContainerServiceFleetManager manager) {
        manager.fleetUpdateStrategies().delete("rgfleets", "fleet1", "fleet1", "saqprswlk",
            com.azure.core.util.Context.NONE);
    }
}
