
/**
 * Samples for Fleets Delete.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-04-01-preview/Fleets_Delete_MaximumSet_Gen.json
     */
    /**
     * Sample code: Deletes a Fleet resource asynchronously with a long running operation. - generated by [MaximumSet]
     * rule.
     * 
     * @param manager Entry point to ContainerServiceFleetManager.
     */
    public static void deletesAFleetResourceAsynchronouslyWithALongRunningOperationGeneratedByMaximumSetRule(
        com.azure.resourcemanager.containerservicefleet.ContainerServiceFleetManager manager) {
        manager.fleets().delete("rgfleets", "fleet1", "crsgokrdxddjsvqxpplerummnmzav",
            com.azure.core.util.Context.NONE);
    }
}
