
/**
 * Samples for UpdateRuns Stop.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-04-01-preview/UpdateRuns_Stop_MaximumSet_Gen.json
     */
    /**
     * Sample code: Stops an UpdateRun. - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to ContainerServiceFleetManager.
     */
    public static void stopsAnUpdateRunGeneratedByMaximumSetRule(
        com.azure.resourcemanager.containerservicefleet.ContainerServiceFleetManager manager) {
        manager.updateRuns().stop("rgfleets", "fleet1", "fleet1", "jb", com.azure.core.util.Context.NONE);
    }
}
