
/**
 * Samples for UpdateRuns Start.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-04-01-preview/UpdateRuns_Start_MaximumSet_Gen.json
     */
    /**
     * Sample code: Starts an UpdateRun. - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to ContainerServiceFleetManager.
     */
    public static void startsAnUpdateRunGeneratedByMaximumSetRule(
        com.azure.resourcemanager.containerservicefleet.ContainerServiceFleetManager manager) {
        manager.updateRuns().start("rgfleets", "fleet1", "fleet1", "bvhjlqeindkmljbbiypbqiaqgtkhlu",
            com.azure.core.util.Context.NONE);
    }
}
