
/**
 * Samples for DiscoverySources Get.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-01-31-preview/DiscoverySources_Get.json
     */
    /**
     * Sample code: DiscoverySources_Get - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to DependencyMapManager.
     */
    public static void discoverySourcesGetGeneratedByMaximumSetRule(
        com.azure.resourcemanager.dependencymap.DependencyMapManager manager) {
        manager.discoverySources().getWithResponse("rgdependencyMap", "mapsTest1", "sourceTest1",
            com.azure.core.util.Context.NONE);
    }
}
