
/**
 * Samples for Maps ListByResourceGroup.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-01-31-preview/Maps_ListByResourceGroup.json
     */
    /**
     * Sample code: Maps_ListByResourceGroup - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to DependencyMapManager.
     */
    public static void mapsListByResourceGroupGeneratedByMaximumSetRule(
        com.azure.resourcemanager.dependencymap.DependencyMapManager manager) {
        manager.maps().listByResourceGroup("rgdependencyMap", com.azure.core.util.Context.NONE);
    }
}
