
import com.azure.resourcemanager.dependencymap.models.MapsResource;
import java.util.HashMap;
import java.util.Map;

/**
 * Samples for Maps Update.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-01-31-preview/Maps_Update.json
     */
    /**
     * Sample code: Maps_Update - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to DependencyMapManager.
     */
    public static void
        mapsUpdateGeneratedByMaximumSetRule(com.azure.resourcemanager.dependencymap.DependencyMapManager manager) {
        MapsResource resource = manager.maps()
            .getByResourceGroupWithResponse("rgdependencyMap", "mapsTest1", com.azure.core.util.Context.NONE)
            .getValue();
        resource.update().withTags(mapOf()).apply();
    }

    // Use "Map.of" if available
    @SuppressWarnings("unchecked")
    private static <T> Map<String, T> mapOf(Object... inputs) {
        Map<String, T> map = new HashMap<>();
        for (int i = 0; i < inputs.length; i += 2) {
            String key = (String) inputs[i];
            T value = (T) inputs[i + 1];
            map.put(key, value);
        }
        return map;
    }
}
