
import com.azure.resourcemanager.dependencymap.models.MapsResourceProperties;
import java.util.HashMap;
import java.util.Map;

/**
 * Samples for Maps CreateOrUpdate.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-01-31-preview/Maps_CreateOrUpdate.json
     */
    /**
     * Sample code: Maps_CreateOrUpdate - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to DependencyMapManager.
     */
    public static void mapsCreateOrUpdateGeneratedByMaximumSetRule(
        com.azure.resourcemanager.dependencymap.DependencyMapManager manager) {
        manager.maps().define("mapsTest1").withRegion("wjtzelgfcmswfeflfltwxqveo")
            .withExistingResourceGroup("rgdependencyMap").withTags(mapOf()).withProperties(new MapsResourceProperties())
            .create();
    }

    // Use "Map.of" if available
    @SuppressWarnings("unchecked")
    private static <T> Map<String, T> mapOf(Object... inputs) {
        Map<String, T> map = new HashMap<>();
        for (int i = 0; i < inputs.length; i += 2) {
            String key = (String) inputs[i];
            T value = (T) inputs[i + 1];
            map.put(key, value);
        }
        return map;
    }
}
