
/**
 * Samples for Maps Delete.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-01-31-preview/Maps_Delete.json
     */
    /**
     * Sample code: Maps_Delete - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to DependencyMapManager.
     */
    public static void
        mapsDeleteGeneratedByMaximumSetRule(com.azure.resourcemanager.dependencymap.DependencyMapManager manager) {
        manager.maps().delete("rgdependencyMap", "mapsTest1", com.azure.core.util.Context.NONE);
    }
}
