
/**
 * Samples for Operations List.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-01-31-preview/Operations_List.json
     */
    /**
     * Sample code: Operations_List - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to DependencyMapManager.
     */
    public static void
        operationsListGeneratedByMaximumSetRule(com.azure.resourcemanager.dependencymap.DependencyMapManager manager) {
        manager.operations().list(com.azure.core.util.Context.NONE);
    }
}
