
import com.azure.resourcemanager.oracledatabase.models.GenerateAutonomousDatabaseWalletDetails;
import com.azure.resourcemanager.oracledatabase.models.GenerateType;

/**
 * Samples for AutonomousDatabases GenerateWallet.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/AutonomousDatabases_GenerateWallet_MaximumSet_Gen.json
     */
    /**
     * Sample code: Generate wallet action on Autonomous Database - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void generateWalletActionOnAutonomousDatabaseGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.autonomousDatabases().generateWalletWithResponse(
            "rgopenapi", "databasedb1", new GenerateAutonomousDatabaseWalletDetails()
                .withGenerateType(GenerateType.SINGLE).withIsRegional(true).withPassword("fakeTokenPlaceholder"),
            com.azure.core.util.Context.NONE);
    }
}
