
/**
 * Samples for AutonomousDatabaseCharacterSets ListByLocation.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/AutonomousDatabaseCharacterSets_ListByLocation_MaximumSet_Gen.json
     */
    /**
     * Sample code: List autonomous db character sets by location - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void listAutonomousDbCharacterSetsByLocationGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.autonomousDatabaseCharacterSets().listByLocation("eastus", com.azure.core.util.Context.NONE);
    }
}
