
import com.azure.resourcemanager.oracledatabase.models.AutonomousDatabaseBackupProperties;

/**
 * Samples for AutonomousDatabaseBackups CreateOrUpdate.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/AutonomousDatabaseBackups_CreateOrUpdate_MaximumSet_Gen.json
     */
    /**
     * Sample code: Create Autonomous Database Backup. - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void createAutonomousDatabaseBackupGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.autonomousDatabaseBackups().define("1711644130")
            .withExistingAutonomousDatabase("rgopenapi", "databasedb1")
            .withProperties(new AutonomousDatabaseBackupProperties().withDisplayName("Nightly Backup")
                .withRetentionPeriodInDays(365))
            .create();
    }
}
