
/**
 * Samples for AutonomousDatabases Delete.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/AutonomousDatabases_Delete_MaximumSet_Gen.json
     */
    /**
     * Sample code: Delete Autonomous Database - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void deleteAutonomousDatabaseGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.autonomousDatabases().delete("rgopenapi", "databasedb1", com.azure.core.util.Context.NONE);
    }
}
