
/**
 * Samples for AutonomousDatabaseVersions ListByLocation.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/AutonomousDatabaseVersions_ListByLocation_MinimumSet_Gen.json
     */
    /**
     * Sample code: List an autonomous versions by location - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void listAnAutonomousVersionsByLocationGeneratedByMinimumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.autonomousDatabaseVersions().listByLocation("eastus", com.azure.core.util.Context.NONE);
    }
}
