
/**
 * Samples for AutonomousDatabaseCharacterSets Get.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/AutonomousDatabaseCharacterSets_Get_MinimumSet_Gen.json
     */
    /**
     * Sample code: Get autonomous db character set - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void getAutonomousDbCharacterSetGeneratedByMinimumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.autonomousDatabaseCharacterSets().getWithResponse("eastus",
            "Replace this value with a string matching RegExp .*", com.azure.core.util.Context.NONE);
    }
}
