
/**
 * Samples for AutonomousDatabases Shrink.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/AutonomousDatabases_Shrink_MaximumSet_Gen.json
     */
    /**
     * Sample code: Perform shrink action on Autonomous Database - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void performShrinkActionOnAutonomousDatabaseGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.autonomousDatabases().shrink("rgopenapi", "database1", com.azure.core.util.Context.NONE);
    }
}
