
import com.azure.resourcemanager.oracledatabase.models.PeerDbDetails;

/**
 * Samples for AutonomousDatabases Switchover.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/AutonomousDatabases_Switchover_MaximumSet_Gen.json
     */
    /**
     * Sample code: Perform switchover action on Autonomous Database - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void performSwitchoverActionOnAutonomousDatabaseGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.autonomousDatabases().switchover(
            "rgopenapi", "databasedb1", new PeerDbDetails().withPeerDbId("peerDbId")
                .withPeerDbOcid("yozpqyefqhirkybmzwgoidyl").withPeerDbLocation("cxlzbzbfzi"),
            com.azure.core.util.Context.NONE);
    }
}
