
/**
 * Samples for AutonomousDatabaseNationalCharacterSets Get.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/AutonomousDatabaseNationalCharacterSets_Get_MinimumSet_Gen.json
     */
    /**
     * Sample code: Get autonomous db national character set - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void getAutonomousDbNationalCharacterSetGeneratedByMinimumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.autonomousDatabaseNationalCharacterSets().getWithResponse("eastus",
            "Replace this value with a string matching RegExp .*", com.azure.core.util.Context.NONE);
    }
}
