
/**
 * Samples for AutonomousDatabases GetByResourceGroup.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/AutonomousDatabases_Get_MaximumSet_Gen.json
     */
    /**
     * Sample code: Get Autonomous Database - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void getAutonomousDatabaseGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.autonomousDatabases().getByResourceGroupWithResponse("rgopenapi", "database1",
            com.azure.core.util.Context.NONE);
    }
}
