
import com.azure.resourcemanager.oracledatabase.models.DisasterRecoveryConfigurationDetails;
import com.azure.resourcemanager.oracledatabase.models.DisasterRecoveryType;
import java.time.OffsetDateTime;

/**
 * Samples for AutonomousDatabases ChangeDisasterRecoveryConfiguration.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/AutonomousDatabases_ChangeDisasterRecoveryConfiguration_MaximumSet_Gen.json
     */
    /**
     * Sample code: Perform ChangeDisasterRecoveryConfiguration action on Autonomous Database - generated by
     * [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void performChangeDisasterRecoveryConfigurationActionOnAutonomousDatabaseGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.autonomousDatabases().changeDisasterRecoveryConfiguration("rgopenapi", "databasedb1",
            new DisasterRecoveryConfigurationDetails().withDisasterRecoveryType(DisasterRecoveryType.ADG)
                .withTimeSnapshotStandbyEnabledTill(OffsetDateTime.parse("2025-08-01T04:32:58.725Z"))
                .withIsSnapshotStandby(true).withIsReplicateAutomaticBackups(true),
            com.azure.core.util.Context.NONE);
    }
}
