
/**
 * Samples for AutonomousDatabaseVersions Get.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/AutonomousDatabaseVersions_Get_MaximumSet_Gen.json
     */
    /**
     * Sample code: Get an autonomous version - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void getAnAutonomousVersionGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.autonomousDatabaseVersions().getWithResponse("eastus",
            "Replace this value with a string matching RegExp .*", com.azure.core.util.Context.NONE);
    }
}
