
/**
 * Samples for AutonomousDatabaseBackups Delete.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/AutonomousDatabaseBackups_Delete_MaximumSet_Gen.json
     */
    /**
     * Sample code: Delete Autonomous Database Backup. - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void deleteAutonomousDatabaseBackupGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.autonomousDatabaseBackups().delete("rgopenapi", "databasedb1", "1711644130",
            com.azure.core.util.Context.NONE);
    }
}
