
/**
 * Samples for AutonomousDatabases ListByResourceGroup.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/AutonomousDatabases_ListByResourceGroup_MinimumSet_Gen.json
     */
    /**
     * Sample code: List Autonomous Database by resource group - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void listAutonomousDatabaseByResourceGroupGeneratedByMinimumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.autonomousDatabases().listByResourceGroup("rgopenapi", com.azure.core.util.Context.NONE);
    }
}
