
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

/**
 * Samples for CloudExadataInfrastructures CreateOrUpdate.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/CloudExadataInfrastructures_CreateOrUpdate_MinimumSet_Gen.json
     */
    /**
     * Sample code: Create Exadata Infrastructure - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void createExadataInfrastructureGeneratedByMinimumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.cloudExadataInfrastructures().define("Replace this value with a string matching RegExp .*")
            .withRegion("eastus").withExistingResourceGroup("rgopenapi").withZones(Arrays.asList("1")).create();
    }

    // Use "Map.of" if available
    @SuppressWarnings("unchecked")
    private static <T> Map<String, T> mapOf(Object... inputs) {
        Map<String, T> map = new HashMap<>();
        for (int i = 0; i < inputs.length; i += 2) {
            String key = (String) inputs[i];
            T value = (T) inputs[i + 1];
            map.put(key, value);
        }
        return map;
    }
}
