
/**
 * Samples for CloudVmClusters Delete.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/CloudVmClusters_Delete_MaximumSet_Gen.json
     */
    /**
     * Sample code: Delete VM Cluster - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void deleteVMClusterGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.cloudVmClusters().delete("rgopenapi", "cloudvmcluster1", com.azure.core.util.Context.NONE);
    }
}
