
import com.azure.resourcemanager.oracledatabase.models.AddRemoveDbNode;
import java.util.Arrays;

/**
 * Samples for CloudVmClusters AddVms.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/CloudVmClusters_AddVms_MaximumSet_Gen.json
     */
    /**
     * Sample code: Add VMs to VM Cluster - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void addVMsToVMClusterGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.cloudVmClusters().addVms("rgopenapi", "cloudvmcluster1",
            new AddRemoveDbNode().withDbServers(Arrays.asList("ocid1..aaaa", "ocid1..aaaaaa")),
            com.azure.core.util.Context.NONE);
    }
}
