
import com.azure.resourcemanager.oracledatabase.models.ConfigureExascaleCloudExadataInfrastructureDetails;

/**
 * Samples for CloudExadataInfrastructures ConfigureExascale.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/CloudExadataInfrastructures_ConfigureExascale_MaximumSet_Gen.json
     */
    /**
     * Sample code: CloudExadataInfrastructures_ConfigureExascale_MaximumSet_Gen - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void cloudExadataInfrastructuresConfigureExascaleMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.cloudExadataInfrastructures().configureExascale("rgopenapi",
            "Replace this value with a string matching RegExp .*",
            new ConfigureExascaleCloudExadataInfrastructureDetails().withTotalStorageInGbs(19),
            com.azure.core.util.Context.NONE);
    }
}
