
import com.azure.resourcemanager.oracledatabase.models.PrivateIpAddressesFilter;

/**
 * Samples for CloudVmClusters ListPrivateIpAddresses.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/CloudVmClusters_ListPrivateIpAddresses_MinimumSet_Gen.json
     */
    /**
     * Sample code: List Private IP Addresses for VM Cluster - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void listPrivateIPAddressesForVMClusterGeneratedByMinimumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.cloudVmClusters().listPrivateIpAddressesWithResponse("rgopenapi", "cloudvmcluster1",
            new PrivateIpAddressesFilter().withSubnetId("ocid1..aaaaaa").withVnicId("ocid1..aaaaa"),
            com.azure.core.util.Context.NONE);
    }
}
