
/**
 * Samples for CloudExadataInfrastructures GetByResourceGroup.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/CloudExadataInfrastructures_Get_MinimumSet_Gen.json
     */
    /**
     * Sample code: Get Exadata Infrastructure - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void getExadataInfrastructureGeneratedByMinimumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.cloudExadataInfrastructures().getByResourceGroupWithResponse("rgopenapi",
            "Replace this value with a string matching RegExp .*", com.azure.core.util.Context.NONE);
    }
}
