
/**
 * Samples for CloudExadataInfrastructures AddStorageCapacity.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/CloudExadataInfrastructures_AddStorageCapacity_MinimumSet_Gen.json
     */
    /**
     * Sample code: Perform add storage capacity on exadata infra - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void performAddStorageCapacityOnExadataInfraGeneratedByMinimumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.cloudExadataInfrastructures().addStorageCapacity("rgopenapi",
            "Replace this value with a string matching RegExp .*", com.azure.core.util.Context.NONE);
    }
}
