
/**
 * Samples for CloudExadataInfrastructures Delete.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/CloudExadataInfrastructures_Delete_MinimumSet_Gen.json
     */
    /**
     * Sample code: Delete Exadata Infrastructure - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void deleteExadataInfrastructureGeneratedByMinimumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.cloudExadataInfrastructures().delete("rgopenapi", "Replace this value with a string matching RegExp .*",
            com.azure.core.util.Context.NONE);
    }
}
