
/**
 * Samples for CloudVmClusters ListByResourceGroup.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/CloudVmClusters_ListByResourceGroup_MaximumSet_Gen.json
     */
    /**
     * Sample code: List VM Clusters by resource group - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void listVMClustersByResourceGroupGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.cloudVmClusters().listByResourceGroup("rgopenapi", com.azure.core.util.Context.NONE);
    }
}
