
import java.util.HashMap;
import java.util.Map;

/**
 * Samples for CloudVmClusters CreateOrUpdate.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/CloudVmClusters_CreateOrUpdate_MinimumSet_Gen.json
     */
    /**
     * Sample code: Create VM Cluster - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void createVMClusterGeneratedByMinimumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.cloudVmClusters().define("cloudvmcluster1").withRegion("eastus").withExistingResourceGroup("rgopenapi")
            .create();
    }

    // Use "Map.of" if available
    @SuppressWarnings("unchecked")
    private static <T> Map<String, T> mapOf(Object... inputs) {
        Map<String, T> map = new HashMap<>();
        for (int i = 0; i < inputs.length; i += 2) {
            String key = (String) inputs[i];
            T value = (T) inputs[i + 1];
            map.put(key, value);
        }
        return map;
    }
}
