
/**
 * Samples for CloudVmClusters List.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/CloudVmClusters_ListBySubscription_MaximumSet_Gen.json
     */
    /**
     * Sample code: List VM Clusters by subscription - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void listVMClustersBySubscriptionGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.cloudVmClusters().list(com.azure.core.util.Context.NONE);
    }
}
