
/**
 * Samples for CloudExadataInfrastructures ListByResourceGroup.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/CloudExadataInfrastructures_ListByResourceGroup_MaximumSet_Gen.json
     */
    /**
     * Sample code: List Exadata Infrastructure by resource group - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void listExadataInfrastructureByResourceGroupGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.cloudExadataInfrastructures().listByResourceGroup("rgopenapi", com.azure.core.util.Context.NONE);
    }
}
