
/**
 * Samples for CloudVmClusters GetByResourceGroup.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/CloudVmClusters_Get_MinimumSet_Gen.json
     */
    /**
     * Sample code: Get VM Cluster - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void
        getVMClusterGeneratedByMinimumSetRule(com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.cloudVmClusters().getByResourceGroupWithResponse("rgopenapi", "cloudvmcluster1",
            com.azure.core.util.Context.NONE);
    }
}
