
/**
 * Samples for DbNodes Get.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/DbNodes_Get_MinimumSet_Gen.json
     */
    /**
     * Sample code: Get DbNode - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void
        getDbNodeGeneratedByMinimumSetRule(com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.dbNodes().getWithResponse("rgopenapi", "Replace this value with a string matching RegExp .*",
            "Replace this value with a string matching RegExp .*", com.azure.core.util.Context.NONE);
    }
}
