
/**
 * Samples for DbNodes Get.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/DbNodes_Get_MaximumSet_Gen.json
     */
    /**
     * Sample code: Get DbNode - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void
        getDbNodeGeneratedByMaximumSetRule(com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.dbNodes().getWithResponse("rgopenapi", "cloudvmcluster1", "weraeefrwlkjejfiepwcd",
            com.azure.core.util.Context.NONE);
    }
}
