
import com.azure.resourcemanager.oracledatabase.models.DbNodeAction;
import com.azure.resourcemanager.oracledatabase.models.DbNodeActionEnum;

/**
 * Samples for DbNodes Action.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/DbNodes_Action_MaximumSet_Gen.json
     */
    /**
     * Sample code: VM actions on DbNodes of VM Cluster - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void vmActionsOnDbNodesOfVMClusterGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.dbNodes().action("rgopenapi", "cloudvmcluster1", "abciderewdidsereq",
            new DbNodeAction().withAction(DbNodeActionEnum.START), com.azure.core.util.Context.NONE);
    }
}
