
/**
 * Samples for DbServers Get.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/DbServers_Get_MinimumSet_Gen.json
     */
    /**
     * Sample code: Get DbServer by parent - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void getDbServerByParentGeneratedByMinimumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.dbServers().getWithResponse("rgopenapi", "Replace this value with a string matching RegExp .*",
            "Replace this value with a string matching RegExp .*", com.azure.core.util.Context.NONE);
    }
}
