
/**
 * Samples for DbSystems List.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/DbSystems_ListBySubscription_MinimumSet_Gen.json
     */
    /**
     * Sample code: DbSystems_ListBySubscription - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void dbSystemsListBySubscriptionGeneratedByMinimumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.dbSystems().list(com.azure.core.util.Context.NONE);
    }
}
