
/**
 * Samples for DbSystemShapes Get.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/DbSystemShapes_Get_MaximumSet_Gen.json
     */
    /**
     * Sample code: Get a DbSystemShape by name - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void getADbSystemShapeByNameGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.dbSystemShapes().getWithResponse("eastus", "dbsystemshape1", com.azure.core.util.Context.NONE);
    }
}
