
/**
 * Samples for DbSystemShapes Get.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/DbSystemShapes_Get_MinimumSet_Gen.json
     */
    /**
     * Sample code: Get a DbSystemShape by name - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void getADbSystemShapeByNameGeneratedByMinimumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.dbSystemShapes().getWithResponse("eastus", "Replace this value with a string matching RegExp .*",
            com.azure.core.util.Context.NONE);
    }
}
