
/**
 * Samples for DbSystems ListByResourceGroup.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/DbSystems_ListByResourceGroup_MinimumSet_Gen.json
     */
    /**
     * Sample code: DbSystems_ListByResourceGroup_MaximumSet_Gen - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void dbSystemsListByResourceGroupMaximumSetGenGeneratedByMinimumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.dbSystems().listByResourceGroup("rgopenapi", com.azure.core.util.Context.NONE);
    }
}
