
/**
 * Samples for DbSystemShapes ListByLocation.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/DbSystemShapes_ListByLocation_MinimumSet_Gen.json
     */
    /**
     * Sample code: List DbSystemShapes by location - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void listDbSystemShapesByLocationGeneratedByMinimumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.dbSystemShapes().listByLocation("eastus", null, null, com.azure.core.util.Context.NONE);
    }
}
