
/**
 * Samples for DnsPrivateZones ListByLocation.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/DnsPrivateZones_ListByLocation_MinimumSet_Gen.json
     */
    /**
     * Sample code: List DnsPrivateZones by location - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void listDnsPrivateZonesByLocationGeneratedByMinimumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.dnsPrivateZones().listByLocation("eastus", com.azure.core.util.Context.NONE);
    }
}
