
/**
 * Samples for DnsPrivateZones Get.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/DnsPrivateZones_Get_MinimumSet_Gen.json
     */
    /**
     * Sample code: Get a DnsPrivateZone by name - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void getADnsPrivateZoneByNameGeneratedByMinimumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.dnsPrivateZones().getWithResponse("eastus", "dnsprivatezone1", com.azure.core.util.Context.NONE);
    }
}
