
/**
 * Samples for DnsPrivateViews ListByLocation.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/DnsPrivateViews_ListByLocation_MaximumSet_Gen.json
     */
    /**
     * Sample code: List DnsPrivateViews by location - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void listDnsPrivateViewsByLocationGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.dnsPrivateViews().listByLocation("eastus", com.azure.core.util.Context.NONE);
    }
}
