
/**
 * Samples for ExadbVmClusters List.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/ExadbVmClusters_ListBySubscription_MinimumSet_Gen.json
     */
    /**
     * Sample code: ExadbVmClusters_ListBySubscription_MaximumSet - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void exadbVmClustersListBySubscriptionMaximumSetGeneratedByMinimumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.exadbVmClusters().list(com.azure.core.util.Context.NONE);
    }
}
