
/**
 * Samples for ExadbVmClusters ListByResourceGroup.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/ExadbVmClusters_ListByResourceGroup_MinimumSet_Gen.json
     */
    /**
     * Sample code: ExadbVmClusters_ListByResourceGroup_MaximumSet - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void exadbVmClustersListByResourceGroupMaximumSetGeneratedByMinimumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.exadbVmClusters().listByResourceGroup("rgopenapi", com.azure.core.util.Context.NONE);
    }
}
