
/**
 * Samples for ExascaleDbNodes Get.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/ExascaleDbNodes_Get_MinimumSet_Gen.json
     */
    /**
     * Sample code: ExascaleDbNodes_Get_MaximumSet - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void exascaleDbNodesGetMaximumSetGeneratedByMinimumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.exascaleDbNodes().getWithResponse("rgopenapi", "vmcluster", "exascaledbnode1",
            com.azure.core.util.Context.NONE);
    }
}
