
import com.azure.resourcemanager.oracledatabase.models.ExascaleDbStorageVault;
import java.util.HashMap;
import java.util.Map;

/**
 * Samples for ExascaleDbStorageVaults Update.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/ExascaleDbStorageVaults_Update_MinimumSet_Gen.json
     */
    /**
     * Sample code: ExascaleDbStorageVaults_Update_MaximumSet - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void exascaleDbStorageVaultsUpdateMaximumSetGeneratedByMinimumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        ExascaleDbStorageVault resource = manager.exascaleDbStorageVaults()
            .getByResourceGroupWithResponse("rgopenapi", "storagevault1", com.azure.core.util.Context.NONE).getValue();
        resource.update().apply();
    }

    // Use "Map.of" if available
    @SuppressWarnings("unchecked")
    private static <T> Map<String, T> mapOf(Object... inputs) {
        Map<String, T> map = new HashMap<>();
        for (int i = 0; i < inputs.length; i += 2) {
            String key = (String) inputs[i];
            T value = (T) inputs[i + 1];
            map.put(key, value);
        }
        return map;
    }
}
