
/**
 * Samples for ExascaleDbStorageVaults GetByResourceGroup.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/ExascaleDbStorageVaults_Get_MinimumSet_Gen.json
     */
    /**
     * Sample code: ExascaleDbStorageVaults_Get_MaximumSet - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void exascaleDbStorageVaultsGetMaximumSetGeneratedByMinimumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.exascaleDbStorageVaults().getByResourceGroupWithResponse("rgopenapi", "storagevault1",
            com.azure.core.util.Context.NONE);
    }
}
