
/**
 * Samples for FlexComponents ListByParent.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/FlexComponents_ListByParent_MinimumSet_Gen.json
     */
    /**
     * Sample code: FlexComponents_ListByParent_MaximumSet - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void flexComponentsListByParentMaximumSetGeneratedByMinimumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.flexComponents().listByParent("eastus", null, com.azure.core.util.Context.NONE);
    }
}
