
/**
 * Samples for GiMinorVersions ListByParent.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/GiMinorVersions_ListByParent_MinimumSet_Gen.json
     */
    /**
     * Sample code: GiMinorVersions_ListByParent_MaximumSet - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void giMinorVersionsListByParentMaximumSetGeneratedByMinimumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.giMinorVersions().listByParent("eastus", "giMinorVersionName", null, null,
            com.azure.core.util.Context.NONE);
    }
}
