
/**
 * Samples for GiVersions Get.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/GiVersions_Get_MaximumSet_Gen.json
     */
    /**
     * Sample code: Get a GiVersion by name - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void getAGiVersionByNameGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.giVersions().getWithResponse("eastus", "giversion1", com.azure.core.util.Context.NONE);
    }
}
