
/**
 * Samples for NetworkAnchors List.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/NetworkAnchors_ListBySubscription_MinimumSet_Gen.json
     */
    /**
     * Sample code: NetworkAnchors_ListBySubscription_MaximumSet - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void networkAnchorsListBySubscriptionMaximumSetGeneratedByMinimumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.networkAnchors().list(com.azure.core.util.Context.NONE);
    }
}
