
/**
 * Samples for Operations List.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/Operations_List_MaximumSet_Gen.json
     */
    /**
     * Sample code: List Operations - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void listOperationsGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.operations().list(com.azure.core.util.Context.NONE);
    }
}
