
/**
 * Samples for OracleSubscriptions ListCloudAccountDetails.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/OracleSubscriptions_ListCloudAccountDetails_MinimumSet_Gen.json
     */
    /**
     * Sample code: List Cloud Account details for the Oracle Subscription - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void listCloudAccountDetailsForTheOracleSubscriptionGeneratedByMinimumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.oracleSubscriptions().listCloudAccountDetails(com.azure.core.util.Context.NONE);
    }
}
