
/**
 * Samples for OracleSubscriptions List.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/OracleSubscriptions_ListBySubscription_MaximumSet_Gen.json
     */
    /**
     * Sample code: List Oracle Subscriptions by subscription - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void listOracleSubscriptionsBySubscriptionGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.oracleSubscriptions().list(com.azure.core.util.Context.NONE);
    }
}
