
/**
 * Samples for OracleSubscriptions ListActivationLinks.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/OracleSubscriptions_ListActivationLinks_MaximumSet_Gen.json
     */
    /**
     * Sample code: List Activation Links for the Oracle Subscription - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void listActivationLinksForTheOracleSubscriptionGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.oracleSubscriptions().listActivationLinks(com.azure.core.util.Context.NONE);
    }
}
