
import com.azure.resourcemanager.oracledatabase.fluent.models.OracleSubscriptionInner;

/**
 * Samples for OracleSubscriptions CreateOrUpdate.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/OracleSubscriptions_CreateOrUpdate_MinimumSet_Gen.json
     */
    /**
     * Sample code: Create or Update Oracle Subscription - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void createOrUpdateOracleSubscriptionGeneratedByMinimumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.oracleSubscriptions().createOrUpdate(new OracleSubscriptionInner(), com.azure.core.util.Context.NONE);
    }
}
