
/**
 * Samples for OracleSubscriptions Delete.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/OracleSubscriptions_Delete_MaximumSet_Gen.json
     */
    /**
     * Sample code: Delete Oracle Subscription - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void deleteOracleSubscriptionGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.oracleSubscriptions().delete(com.azure.core.util.Context.NONE);
    }
}
