
/**
 * Samples for OracleSubscriptions Get.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/OracleSubscriptions_Get_MinimumSet_Gen.json
     */
    /**
     * Sample code: Get Oracle Subscription - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void getOracleSubscriptionGeneratedByMinimumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.oracleSubscriptions().getWithResponse(com.azure.core.util.Context.NONE);
    }
}
