
/**
 * Samples for ResourceAnchors List.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/ResourceAnchors_ListBySubscription_MinimumSet_Gen.json
     */
    /**
     * Sample code: ResourceAnchors_ListBySubscription_MaximumSet - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void resourceAnchorsListBySubscriptionMaximumSetGeneratedByMinimumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.resourceAnchors().list(com.azure.core.util.Context.NONE);
    }
}
