
/**
 * Samples for SystemVersions Get.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/SystemVersions_Get_MaximumSet_Gen.json
     */
    /**
     * Sample code: Get Exadata System Version - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void getExadataSystemVersionGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.systemVersions().getWithResponse("eastus", "Replace this value with a string matching RegExp .*",
            com.azure.core.util.Context.NONE);
    }
}
