
/**
 * Samples for VirtualNetworkAddresses Delete.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/VirtualNetworkAddresses_Delete_MaximumSet_Gen.json
     */
    /**
     * Sample code: Delete Virtual Network Address - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void deleteVirtualNetworkAddressGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.virtualNetworkAddresses().delete("rgopenapi", "Replace this value with a string matching RegExp .*",
            "Replace this value with a string matching RegExp .*", com.azure.core.util.Context.NONE);
    }
}
