
import com.azure.resourcemanager.oracledatabase.models.VirtualNetworkAddressProperties;

/**
 * Samples for VirtualNetworkAddresses CreateOrUpdate.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/VirtualNetworkAddresses_CreateOrUpdate_MaximumSet_Gen.json
     */
    /**
     * Sample code: Create Virtual Network Address - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void createVirtualNetworkAddressGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.virtualNetworkAddresses().define("Replace this value with a string matching RegExp .*")
            .withExistingCloudVmCluster("rgopenapi", "Replace this value with a string matching RegExp .*")
            .withProperties(
                new VirtualNetworkAddressProperties().withIpAddress("192.168.0.1").withVmOcid("ocid1..aaaa"))
            .create();
    }
}
