
/**
 * Samples for VirtualNetworkAddresses Get.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/VirtualNetworkAddresses_Get_MinimumSet_Gen.json
     */
    /**
     * Sample code: Get Virtual Network Address - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void getVirtualNetworkAddressGeneratedByMinimumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.virtualNetworkAddresses().getWithResponse("rgopenapi",
            "Replace this value with a string matching RegExp .*",
            "Replace this value with a string matching RegExp .*", com.azure.core.util.Context.NONE);
    }
}
