
/**
 * Samples for VirtualNetworkAddresses CreateOrUpdate.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-09-01/VirtualNetworkAddresses_CreateOrUpdate_MinimumSet_Gen.json
     */
    /**
     * Sample code: Create Virtual Network Address - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void createVirtualNetworkAddressGeneratedByMinimumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.virtualNetworkAddresses().define("Replace this value with a string matching RegExp .*")
            .withExistingCloudVmCluster("rgopenapi", "Replace this value with a string matching RegExp .*").create();
    }
}
