
import com.azure.resourcemanager.oracledatabase.models.AutonomousDatabaseLifecycleAction;
import com.azure.resourcemanager.oracledatabase.models.AutonomousDatabaseLifecycleActionEnum;

/**
 * Samples for AutonomousDatabases Action.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-06-01/AutonomousDatabases_Action_MaximumSet_Gen.json
     */
    /**
     * Sample code: AutonomousDatabases_Action_MaximumSet_Gen - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void autonomousDatabasesActionMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.autonomousDatabases().action("rgopenapi", "resource1",
            new AutonomousDatabaseLifecycleAction().withAction(AutonomousDatabaseLifecycleActionEnum.START),
            com.azure.core.util.Context.NONE);
    }
}
