
/**
 * Samples for DatabaseEditions Get.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-06-01/DatabaseEditions_Get_MaximumSet_Gen.json
     */
    /**
     * Sample code: DatabaseEditions_Get_MaximumSet_Gen - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void databaseEditionsGetMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.databaseEditions().getWithResponse("eastus", "resource1", com.azure.core.util.Context.NONE);
    }
}
