
/**
 * Samples for DatabaseSystemShapeResources ListByLocation.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-06-01/DatabaseSystemShapeResources_ListByLocation_MaximumSet_Gen.json
     */
    /**
     * Sample code: DatabaseSystemShapeResources_ListByLocation_MaximumSet_Gen - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void databaseSystemShapeResourcesListByLocationMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.databaseSystemShapeResources().listByLocation("eastus", "example", "bxkklcsc", "njeq", "example",
            "example", com.azure.core.util.Context.NONE);
    }
}
