
/**
 * Samples for DatabaseSystemShapeResources Get.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-06-01/DatabaseSystemShapeResources_Get_MaximumSet_Gen.json
     */
    /**
     * Sample code: DatabaseSystemShapeResources_Get_MaximumSet_Gen - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void databaseSystemShapeResourcesGetMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.databaseSystemShapeResources().getWithResponse("eastus", "resource1", com.azure.core.util.Context.NONE);
    }
}
