
/**
 * Samples for DatabaseEditions ListByLocation.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-06-01/DatabaseEditions_ListByLocation_MaximumSet_Gen.json
     */
    /**
     * Sample code: DatabaseEditions_ListByLocation_MaximumSet_Gen - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void databaseEditionsListByLocationMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.databaseEditions().listByLocation("eastus", com.azure.core.util.Context.NONE);
    }
}
