
/**
 * Samples for DbSystems List.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-06-01/DbSystems_ListBySubscription_MaximumSet_Gen.json
     */
    /**
     * Sample code: DbSystems_ListBySubscription_MaximumSet_Gen - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void dbSystemsListBySubscriptionMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.dbSystems().list(com.azure.core.util.Context.NONE);
    }
}
