
/**
 * Samples for DbSystems GetByResourceGroup.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-06-01/DbSystems_Get_MaximumSet_Gen.json
     */
    /**
     * Sample code: DbSystems_Get_MaximumSet_Gen - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void dbSystemsGetMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.dbSystems().getByResourceGroupWithResponse("rgopenapi", "resource1", com.azure.core.util.Context.NONE);
    }
}
