
import com.azure.resourcemanager.oracledatabase.models.BaseDbSystemShapes;
import com.azure.resourcemanager.oracledatabase.models.ShapeFamilyType;
import com.azure.resourcemanager.oracledatabase.models.StorageManagementType;

/**
 * Samples for DbVersions ListByLocation.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-06-01/DbVersions_ListByLocation_MaximumSet_Gen.json
     */
    /**
     * Sample code: DbVersions_ListByLocation_MaximumSet_Gen - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void dbVersionsListByLocationMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.dbVersions().listByLocation("eastus", BaseDbSystemShapes.VMSTANDARD_X86,
            "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg000/providers/Oracle.Database/dbSystems/db1",
            StorageManagementType.LVM, true, true, ShapeFamilyType.EXADATA, com.azure.core.util.Context.NONE);
    }
}
