
/**
 * Samples for ExadbVmClusters List.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-06-01/ExadbVmClusters_ListBySubscription_MaximumSet_Gen.json
     */
    /**
     * Sample code: ExadbVmClusters_ListBySubscription_MaximumSet_Gen - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void exadbVmClustersListBySubscriptionMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.exadbVmClusters().list(com.azure.core.util.Context.NONE);
    }
}
