
import com.azure.resourcemanager.oracledatabase.models.DbNodeDetails;
import com.azure.resourcemanager.oracledatabase.models.RemoveVirtualMachineFromExadbVmClusterDetails;
import java.util.Arrays;

/**
 * Samples for ExadbVmClusters RemoveVms.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-06-01/ExadbVmClusters_RemoveVms_MaximumSet_Gen.json
     */
    /**
     * Sample code: ExadbVmClusters_RemoveVms_MaximumSet_Gen - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void exadbVmClustersRemoveVmsMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.exadbVmClusters().removeVms("rgopenapi", "resource1",
            new RemoveVirtualMachineFromExadbVmClusterDetails()
                .withDbNodes(Arrays.asList(new DbNodeDetails().withDbNodeId(
                    "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg000/providers/Oracle.Database/exadbVmClusters/vmcluster1/dbNodes/node1"))),
            com.azure.core.util.Context.NONE);
    }
}
