
/**
 * Samples for ExadbVmClusters ListByResourceGroup.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-06-01/ExadbVmClusters_ListByResourceGroup_MaximumSet_Gen.json
     */
    /**
     * Sample code: ExadbVmClusters_ListByResourceGroup_MaximumSet_Gen - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void exadbVmClustersListByResourceGroupMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.exadbVmClusters().listByResourceGroup("rgopenapi", com.azure.core.util.Context.NONE);
    }
}
