
/**
 * Samples for ExadbVmClusters Delete.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-06-01/ExadbVmClusters_Delete_MaximumSet_Gen.json
     */
    /**
     * Sample code: ExadbVmClusters_Delete_MaximumSet_Gen - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void exadbVmClustersDeleteMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.exadbVmClusters().delete("rgopenapi", "resource1", com.azure.core.util.Context.NONE);
    }
}
