
/**
 * Samples for ExascaleDbStorageVaults ListByResourceGroup.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-06-01/ExascaleDbStorageVaults_ListByResourceGroup_MaximumSet_Gen.json
     */
    /**
     * Sample code: ExascaleDbStorageVaults_ListByResourceGroup_MaximumSet_Gen - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void exascaleDbStorageVaultsListByResourceGroupMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.exascaleDbStorageVaults().listByResourceGroup("rgopenapi", com.azure.core.util.Context.NONE);
    }
}
