
/**
 * Samples for ExascaleDbStorageVaults Delete.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-06-01/ExascaleDbStorageVaults_Delete_MaximumSet_Gen.json
     */
    /**
     * Sample code: ExascaleDbStorageVaults_Delete_MaximumSet_Gen - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void exascaleDbStorageVaultsDeleteMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.exascaleDbStorageVaults().delete("rgopenapi", "resource1", com.azure.core.util.Context.NONE);
    }
}
