
/**
 * Samples for FlexComponents Get.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-06-01/FlexComponents_Get_MaximumSet_Gen.json
     */
    /**
     * Sample code: FlexComponents_Get_MaximumSet_Gen - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void flexComponentsGetMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.flexComponents().getWithResponse("eastus", "resource1", com.azure.core.util.Context.NONE);
    }
}
