
import com.azure.resourcemanager.oracledatabase.models.GiMinorVersionSortOrder;
import com.azure.resourcemanager.oracledatabase.models.ShapeFamily;

/**
 * Samples for GiMinorVersions ListByParent.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-06-01/GiMinorVersions_ListByParent_MaximumSet_Gen.json
     */
    /**
     * Sample code: GiMinorVersions_ListByParent_MaximumSet_Gen - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void giMinorVersionsListByParentMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.giMinorVersions().listByParent("eastus", "resource1", ShapeFamily.EXADATA, "o", "example", true,
            GiMinorVersionSortOrder.ASC, com.azure.core.util.Context.NONE);
    }
}
