
/**
 * Samples for GiMinorVersions Get.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-06-01/GiMinorVersions_Get_MaximumSet_Gen.json
     */
    /**
     * Sample code: GiMinorVersions_Get_MaximumSet_Gen - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void giMinorVersionsGetMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.giMinorVersions().getWithResponse("eastus", "resource1", "resource1", com.azure.core.util.Context.NONE);
    }
}
