
import com.azure.resourcemanager.oracledatabase.models.SystemShapes;

/**
 * Samples for GiVersions ListByLocation.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-06-01/GiVersions_ListByLocation_MaximumSet_Gen.json
     */
    /**
     * Sample code: GiVersions_ListByLocation_MaximumSet_Gen - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void giVersionsListByLocationMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.giVersions().listByLocation("eastus", SystemShapes.EXADATA_X9M, "example", "bmr",
            com.azure.core.util.Context.NONE);
    }
}
