
/**
 * Samples for GoldenGateDeployments GetByResourceGroup.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-06-01/GoldenGateDeployments_Get_MaximumSet_Gen.json
     */
    /**
     * Sample code: GoldenGateDeployments_Get_MaximumSet_Gen - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void goldenGateDeploymentsGetMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.goldenGateDeployments().getByResourceGroupWithResponse("rgopenapi", "resource1",
            com.azure.core.util.Context.NONE);
    }
}
