
/**
 * Samples for GoldenGateDeployments ListAssignedConnectionsByParent.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-06-01/GoldenGateDeployments_ListAssignedConnectionsByParent_MaximumSet_Gen.json
     */
    /**
     * Sample code: GoldenGateDeployments_ListAssignedConnectionsByParent_MaximumSet_Gen - generated by [MaximumSet]
     * rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void goldenGateDeploymentsListAssignedConnectionsByParentMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.goldenGateDeployments().listAssignedConnectionsByParent("rgopenapi", "resource1",
            com.azure.core.util.Context.NONE);
    }
}
