
/**
 * Samples for GoldenGateConnections List.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-06-01/GoldenGateConnections_ListBySubscription_MaximumSet_Gen.json
     */
    /**
     * Sample code: GoldenGateConnections_ListBySubscription_MaximumSet_Gen - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void goldenGateConnectionsListBySubscriptionMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.goldenGateConnections().list(com.azure.core.util.Context.NONE);
    }
}
