
import com.azure.resourcemanager.oracledatabase.models.AssignUnassignConnection;

/**
 * Samples for GoldenGateDeployments AssignConnection.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-06-01/GoldenGateDeployments_AssignConnection_MaximumSet_Gen.json
     */
    /**
     * Sample code: GoldenGateDeployments_AssignConnection_MaximumSet_Gen - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void goldenGateDeploymentsAssignConnectionMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.goldenGateDeployments().assignConnection("rgopenapi", "resource1",
            new AssignUnassignConnection().withConnectionId(
                "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg000/providers/Oracle.Database/resources/resource1"),
            com.azure.core.util.Context.NONE);
    }
}
