
/**
 * Samples for GoldenGateConnections GetAssignedDeployment.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-06-01/GoldenGateConnections_GetAssignedDeployment_MaximumSet_Gen.json
     */
    /**
     * Sample code: GoldenGateConnections_GetAssignedDeployment_MaximumSet_Gen - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void goldenGateConnectionsGetAssignedDeploymentMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.goldenGateConnections().getAssignedDeploymentWithResponse("rgopenapi", "resource1", "assignment1",
            com.azure.core.util.Context.NONE);
    }
}
