
/**
 * Samples for GoldenGateConnections ListAssignedDeploymentsByParent.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-06-01/GoldenGateConnections_ListAssignedDeploymentsByParent_MaximumSet_Gen.json
     */
    /**
     * Sample code: GoldenGateConnections_ListAssignedDeploymentsByParent_MaximumSet_Gen - generated by [MaximumSet]
     * rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void goldenGateConnectionsListAssignedDeploymentsByParentMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.goldenGateConnections().listAssignedDeploymentsByParent("rgopenapi", "resource1",
            com.azure.core.util.Context.NONE);
    }
}
