
/**
 * Samples for GoldenGateConnections Delete.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-06-01/GoldenGateConnections_Delete_MaximumSet_Gen.json
     */
    /**
     * Sample code: GoldenGateConnections_Delete_MaximumSet_Gen - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void goldenGateConnectionsDeleteMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.goldenGateConnections().delete("rgopenapi", "resource1", com.azure.core.util.Context.NONE);
    }
}
