
/**
 * Samples for GoldenGateDeployments GetAssignedConnection.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-06-01/GoldenGateDeployments_GetAssignedConnection_MaximumSet_Gen.json
     */
    /**
     * Sample code: GoldenGateDeployments_GetAssignedConnection_MaximumSet_Gen - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void goldenGateDeploymentsGetAssignedConnectionMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.goldenGateDeployments().getAssignedConnectionWithResponse("rgopenapi", "resource1", "assignment1",
            com.azure.core.util.Context.NONE);
    }
}
