
/**
 * Samples for GoldenGateDeployments List.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-06-01/GoldenGateDeployments_ListBySubscription_MaximumSet_Gen.json
     */
    /**
     * Sample code: GoldenGateDeployments_ListBySubscription_MaximumSet_Gen - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void goldenGateDeploymentsListBySubscriptionMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.goldenGateDeployments().list(com.azure.core.util.Context.NONE);
    }
}
