
/**
 * Samples for GoldenGateConnections GetByResourceGroup.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-06-01/GoldenGateConnections_Get_MaximumSet_Gen.json
     */
    /**
     * Sample code: GoldenGateConnections_Get_MaximumSet_Gen - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void goldenGateConnectionsGetMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.goldenGateConnections().getByResourceGroupWithResponse("rgopenapi", "resource1",
            com.azure.core.util.Context.NONE);
    }
}
