
/**
 * Samples for NetworkAnchors Delete.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-06-01/NetworkAnchors_Delete_MaximumSet_Gen.json
     */
    /**
     * Sample code: NetworkAnchors_Delete_MaximumSet_Gen - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void networkAnchorsDeleteMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.networkAnchors().delete("rgopenapi", "resource1", com.azure.core.util.Context.NONE);
    }
}
