
/**
 * Samples for NetworkAnchors List.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-06-01/NetworkAnchors_ListBySubscription_MaximumSet_Gen.json
     */
    /**
     * Sample code: NetworkAnchors_ListBySubscription_MaximumSet_Gen - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void networkAnchorsListBySubscriptionMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.networkAnchors().list(com.azure.core.util.Context.NONE);
    }
}
