
/**
 * Samples for ResourceAnchors List.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-06-01/ResourceAnchors_ListBySubscription_MaximumSet_Gen.json
     */
    /**
     * Sample code: ResourceAnchors_ListBySubscription_MaximumSet_Gen - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void resourceAnchorsListBySubscriptionMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.resourceAnchors().list(com.azure.core.util.Context.NONE);
    }
}
