
/**
 * Samples for ResourceAnchors GetByResourceGroup.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-06-01/ResourceAnchors_Get_MaximumSet_Gen.json
     */
    /**
     * Sample code: ResourceAnchors_Get_MaximumSet_Gen - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void resourceAnchorsGetMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.resourceAnchors().getByResourceGroupWithResponse("rgopenapi", "resource1",
            com.azure.core.util.Context.NONE);
    }
}
