
import com.azure.resourcemanager.containerregistry.models.AutoGeneratedDomainNameLabelScope;
import com.azure.resourcemanager.containerregistry.models.RegistryNameCheckRequest;

/**
 * Samples for Registries CheckNameAvailability.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-03-01-preview/RegistryCheckNameAvailable.json
     */
    /**
     * Sample code: RegistryCheckNameAvailable.
     * 
     * @param manager Entry point to ContainerRegistryManager.
     */
    public static void
        registryCheckNameAvailable(com.azure.resourcemanager.containerregistry.ContainerRegistryManager manager) {
        manager.serviceClient().getRegistries().checkNameAvailabilityWithResponse(
            new RegistryNameCheckRequest().withName("myRegistry").withResourceGroupName("myResourceGroup")
                .withAutoGeneratedDomainNameLabelScope(AutoGeneratedDomainNameLabelScope.RESOURCE_GROUP_REUSE),
            com.azure.core.util.Context.NONE);
    }
}
