
/**
 * Samples for Organizations ListByResourceGroup.
 */
public final class Main {
    /*
     * x-ms-original-file: 2024-10-01/Organizations_ListByResourceGroup_MaximumSet_Gen.json
     */
    /**
     * Sample code: Organizations_ListByResourceGroup - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to ArizeAIObservabilityEvalManager.
     */
    public static void organizationsListByResourceGroupGeneratedByMaximumSetRule(
        com.azure.resourcemanager.arizeaiobservabilityeval.ArizeAIObservabilityEvalManager manager) {
        manager.organizations().listByResourceGroup("rgopenapi", com.azure.core.util.Context.NONE);
    }
}
