
/**
 * Samples for Organizations GetByResourceGroup.
 */
public final class Main {
    /*
     * x-ms-original-file: 2024-10-01/Organizations_Get_MaximumSet_Gen.json
     */
    /**
     * Sample code: Organizations_Get - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to ArizeAIObservabilityEvalManager.
     */
    public static void organizationsGetGeneratedByMaximumSetRule(
        com.azure.resourcemanager.arizeaiobservabilityeval.ArizeAIObservabilityEvalManager manager) {
        manager.organizations().getByResourceGroupWithResponse("rgopenapi", "test-organization-1",
            com.azure.core.util.Context.NONE);
    }
}
