
/**
 * Samples for Organizations List.
 */
public final class Main {
    /*
     * x-ms-original-file: 2024-10-01/Organizations_ListBySubscription_MaximumSet_Gen.json
     */
    /**
     * Sample code: Organizations_ListBySubscription - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to ArizeAIObservabilityEvalManager.
     */
    public static void organizationsListBySubscriptionGeneratedByMaximumSetRule(
        com.azure.resourcemanager.arizeaiobservabilityeval.ArizeAIObservabilityEvalManager manager) {
        manager.organizations().list(com.azure.core.util.Context.NONE);
    }
}
