
import com.azure.resourcemanager.compute.models.DiskUpdate;
import com.azure.resourcemanager.compute.models.PurchasePlanAutoGenerated;

/**
 * Samples for Disks Update.
 */
public final class Main {
    /*
     * x-ms-original-file:
     * specification/compute/resource-manager/Microsoft.Compute/DiskRP/stable/2024-03-02/examples/diskExamples/
     * Disk_Update_AddPurchasePlan.json
     */
    /**
     * Sample code: Update a managed disk to add purchase plan.
     * 
     * @param azure The entry point for accessing resource management APIs in Azure.
     */
    public static void updateAManagedDiskToAddPurchasePlan(com.azure.resourcemanager.AzureResourceManager azure) {
        azure.virtualMachines().manager().serviceClient().getDisks()
            .update("myResourceGroup", "myDisk",
                new DiskUpdate().withPurchasePlan(new PurchasePlanAutoGenerated().withName("myPurchasePlanName")
                    .withPublisher("myPurchasePlanPublisher").withProduct("myPurchasePlanProduct")
                    .withPromotionCode("fakeTokenPlaceholder")),
                com.azure.core.util.Context.NONE);
    }
}
