
/**
 * Samples for BulkActions Get.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-02-01-preview/BulkActions_Get_MaximumSet_Gen.json
     */
    /**
     * Sample code: BulkActions_Get - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to ComputeBulkActionsManager.
     */
    public static void bulkActionsGetGeneratedByMaximumSetRule(
        com.azure.resourcemanager.computebulkactions.ComputeBulkActionsManager manager) {
        manager.bulkActions().getWithResponse("rgcomputebulkactions", "eastus2euap",
            "3ec2ab23-9f13-4328-85c8-21928acbc7b8", com.azure.core.util.Context.NONE);
    }
}
