
/**
 * Samples for BulkActions ListByResourceGroup.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-02-01-preview/BulkActions_ListByResourceGroup_MaximumSet_Gen.json
     */
    /**
     * Sample code: BulkActions_ListByResourceGroup - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to ComputeBulkActionsManager.
     */
    public static void bulkActionsListByResourceGroupGeneratedByMaximumSetRule(
        com.azure.resourcemanager.computebulkactions.ComputeBulkActionsManager manager) {
        manager.bulkActions().listByResourceGroup("rgcomputebulkactions", "eastus2euap",
            com.azure.core.util.Context.NONE);
    }
}
