
import com.azure.resourcemanager.computebulkactions.models.ExecuteCreateRequest;
import com.azure.resourcemanager.computebulkactions.models.ExecutionParameters;
import com.azure.resourcemanager.computebulkactions.models.ResourceProvisionPayload;
import java.util.HashMap;
import java.util.Map;

/**
 * Samples for BulkActions VirtualMachinesExecuteCreate.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-02-01-preview/BulkActions_VirtualMachinesExecuteCreate_MinimumSet_Gen.json
     */
    /**
     * Sample code: BulkActions_VirtualMachinesExecuteCreate_MinimumSet_Gen - generated by [MinimumSet] rule - generated
     * by [MinimumSet] rule.
     * 
     * @param manager Entry point to ComputeBulkActionsManager.
     */
    public static void
        bulkActionsVirtualMachinesExecuteCreateMinimumSetGenGeneratedByMinimumSetRuleGeneratedByMinimumSetRule(
            com.azure.resourcemanager.computebulkactions.ComputeBulkActionsManager manager) {
        manager.bulkActions().virtualMachinesExecuteCreateWithResponse("eastus2euap",
            new ExecuteCreateRequest().withResourceConfigParameters(new ResourceProvisionPayload().withResourceCount(1))
                .withExecutionParameters(new ExecutionParameters()),
            com.azure.core.util.Context.NONE);
    }

    // Use "Map.of" if available
    @SuppressWarnings("unchecked")
    private static <T> Map<String, T> mapOf(Object... inputs) {
        Map<String, T> map = new HashMap<>();
        for (int i = 0; i < inputs.length; i += 2) {
            String key = (String) inputs[i];
            T value = (T) inputs[i + 1];
            map.put(key, value);
        }
        return map;
    }
}
