
import com.azure.resourcemanager.computebulkactions.models.CancelOperationsRequest;
import java.util.Arrays;

/**
 * Samples for BulkActions VirtualMachinesCancelOperations.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-02-01-preview/BulkActions_VirtualMachinesCancelOperations_MaximumSet_Gen.json
     */
    /**
     * Sample code: BulkActions_VirtualMachinesCancelOperations_MaximumSet_Gen - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to ComputeBulkActionsManager.
     */
    public static void bulkActionsVirtualMachinesCancelOperationsMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.computebulkactions.ComputeBulkActionsManager manager) {
        manager.bulkActions().virtualMachinesCancelOperationsWithResponse("eastus2euap",
            new CancelOperationsRequest().withOperationIds(Arrays.asList("2a3fce8e-874c-45f4-9d27-1a804f3b7a0f"))
                .withCorrelationId("4431320c-7a90-4300-b82b-73f0696ae50e"),
            com.azure.core.util.Context.NONE);
    }
}
