
import com.azure.resourcemanager.computebulkactions.models.ExecuteHibernateRequest;
import com.azure.resourcemanager.computebulkactions.models.ExecutionParameters;
import com.azure.resourcemanager.computebulkactions.models.Resources;
import com.azure.resourcemanager.computebulkactions.models.RetryPolicy;
import java.util.Arrays;

/**
 * Samples for BulkActions VirtualMachinesExecuteHibernate.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-02-01-preview/BulkActions_VirtualMachinesExecuteHibernate_MaximumSet_Gen.json
     */
    /**
     * Sample code: BulkActions_VirtualMachinesExecuteHibernate_MaximumSet_Gen - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to ComputeBulkActionsManager.
     */
    public static void bulkActionsVirtualMachinesExecuteHibernateMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.computebulkactions.ComputeBulkActionsManager manager) {
        manager.bulkActions().virtualMachinesExecuteHibernateWithResponse("eastus2euap", new ExecuteHibernateRequest()
            .withExecutionParameters(new ExecutionParameters()
                .withRetryPolicy(new RetryPolicy().withRetryCount(5).withRetryWindowInMinutes(27)))
            .withResources(new Resources().withIds(Arrays.asList(
                "/subscriptions/YourSubscriptionId/resourceGroups/YourResourceGroupName/providers/Microsoft.Compute/virtualMachines/testResource3")))
            .withCorrelationId("4431320c-7a90-4300-b82b-73f0696ae50e"), com.azure.core.util.Context.NONE);
    }
}
