
/**
 * Samples for BulkActions GetOperationStatus.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-02-01-preview/BulkActions_GetOperationStatus_MaximumSet_Gen.json
     */
    /**
     * Sample code: BulkActions_GetOperationStatus - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to ComputeBulkActionsManager.
     */
    public static void bulkActionsGetOperationStatusGeneratedByMaximumSetRule(
        com.azure.resourcemanager.computebulkactions.ComputeBulkActionsManager manager) {
        manager.bulkActions().getOperationStatusWithResponse("eastus2euap", "2a3fce8e-874c-45f4-9d27-1a804f3b7a0f",
            com.azure.core.util.Context.NONE);
    }
}
