
import com.azure.resourcemanager.computebulkactions.models.GetOperationStatusRequest;
import java.util.Arrays;

/**
 * Samples for BulkActions VirtualMachinesGetOperationStatus.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-02-01-preview/BulkActions_VirtualMachinesGetOperationStatus_MinimumSet_Gen.json
     */
    /**
     * Sample code: BulkActions_VirtualMachinesGetOperationStatus_MinimumSet_Gen - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to ComputeBulkActionsManager.
     */
    public static void bulkActionsVirtualMachinesGetOperationStatusMinimumSetGenGeneratedByMinimumSetRule(
        com.azure.resourcemanager.computebulkactions.ComputeBulkActionsManager manager) {
        manager.bulkActions().virtualMachinesGetOperationStatusWithResponse("eastus2euap",
            new GetOperationStatusRequest().withOperationIds(Arrays.asList("23480d2f-1dca-4610-afb4-dd25eec1f34r"))
                .withCorrelationId("4431320c-7a90-4300-b82b-73f0696ae50e"),
            com.azure.core.util.Context.NONE);
    }
}
