
/**
 * Samples for BulkActions Delete.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-02-01-preview/BulkActions_Delete_MaximumSet_Gen.json
     */
    /**
     * Sample code: BulkActions_Delete - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to ComputeBulkActionsManager.
     */
    public static void bulkActionsDeleteGeneratedByMaximumSetRule(
        com.azure.resourcemanager.computebulkactions.ComputeBulkActionsManager manager) {
        manager.bulkActions().delete("rgcomputebulkactions", "eastus2euap", "3ec2ab23-9f13-4328-85c8-21928acbc7b8",
            null, com.azure.core.util.Context.NONE);
    }
}
