
import com.azure.resourcemanager.computebulkactions.models.ExecuteDeleteRequest;
import com.azure.resourcemanager.computebulkactions.models.ExecutionParameters;
import com.azure.resourcemanager.computebulkactions.models.Resources;
import com.azure.resourcemanager.computebulkactions.models.RetryPolicy;
import java.util.Arrays;

/**
 * Samples for BulkActions VirtualMachinesExecuteDelete.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-02-01-preview/BulkActions_VirtualMachinesExecuteDelete_MaximumSet_Gen.json
     */
    /**
     * Sample code: BulkActions_VirtualMachinesExecuteDelete_MaximumSet_Gen - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to ComputeBulkActionsManager.
     */
    public static void bulkActionsVirtualMachinesExecuteDeleteMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.computebulkactions.ComputeBulkActionsManager manager) {
        manager.bulkActions().virtualMachinesExecuteDeleteWithResponse("east2us2euap", new ExecuteDeleteRequest()
            .withExecutionParameters(new ExecutionParameters()
                .withRetryPolicy(new RetryPolicy().withRetryCount(2).withRetryWindowInMinutes(45)))
            .withResources(new Resources().withIds(Arrays.asList(
                "/subscriptions/YourSubscriptionId/resourceGroups/YourResourceGroupName/providers/Microsoft.Compute/virtualMachines/testResource3",
                "/subscriptions/YourSubscriptionId/resourceGroups/YourResourceGroupName/providers/Microsoft.Compute/virtualMachines/testResource4")))
            .withCorrelationId("dfe927c5-16a6-40b7-a0f7-8524975ed642").withForceDeletion(true),
            com.azure.core.util.Context.NONE);
    }
}
