
/**
 * Samples for BulkActions ListBySubscription.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-02-01-preview/BulkActions_ListBySubscription_MinimumSet_Gen.json
     */
    /**
     * Sample code: BulkActions_ListBySubscription - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to ComputeBulkActionsManager.
     */
    public static void bulkActionsListBySubscriptionGeneratedByMinimumSetRule(
        com.azure.resourcemanager.computebulkactions.ComputeBulkActionsManager manager) {
        manager.bulkActions().listBySubscription("eastus2euap", com.azure.core.util.Context.NONE);
    }
}
