
import com.azure.resourcemanager.computebulkactions.models.CancelOperationsRequest;
import java.util.Arrays;

/**
 * Samples for BulkActions VirtualMachinesCancelOperations.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-02-01-preview/BulkActions_VirtualMachinesCancelOperations_MinimumSet_Gen.json
     */
    /**
     * Sample code: BulkActions_VirtualMachinesCancelOperations_MaximumSet_Gen - generated by [MaximumSet] rule -
     * generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to ComputeBulkActionsManager.
     */
    public static void
        bulkActionsVirtualMachinesCancelOperationsMaximumSetGenGeneratedByMaximumSetRuleGeneratedByMinimumSetRule(
            com.azure.resourcemanager.computebulkactions.ComputeBulkActionsManager manager) {
        manager.bulkActions().virtualMachinesCancelOperationsWithResponse("eastus2euap",
            new CancelOperationsRequest().withOperationIds(Arrays.asList("23480d2f-1dca-4610-afb4-dd25eec1f34r"))
                .withCorrelationId("4431320c-7a90-4300-b82b-73f0696ae50e"),
            com.azure.core.util.Context.NONE);
    }
}
