
import com.azure.resourcemanager.computebulkactions.models.ExecuteHibernateRequest;
import com.azure.resourcemanager.computebulkactions.models.ExecutionParameters;
import com.azure.resourcemanager.computebulkactions.models.Resources;
import java.util.Arrays;

/**
 * Samples for BulkActions VirtualMachinesExecuteHibernate.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-02-01-preview/BulkActions_VirtualMachinesExecuteHibernate_MinimumSet_Gen.json
     */
    /**
     * Sample code: BulkActions_VirtualMachinesExecuteHibernate_MinimumSet_Gen - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to ComputeBulkActionsManager.
     */
    public static void bulkActionsVirtualMachinesExecuteHibernateMinimumSetGenGeneratedByMinimumSetRule(
        com.azure.resourcemanager.computebulkactions.ComputeBulkActionsManager manager) {
        manager.bulkActions().virtualMachinesExecuteHibernateWithResponse("acuh", new ExecuteHibernateRequest()
            .withExecutionParameters(new ExecutionParameters())
            .withResources(new Resources().withIds(Arrays.asList(
                "/subscriptions/YourSubscriptionId/resourceGroups/YourResourceGroupName/providers/Microsoft.Compute/virtualMachines/testResource3")))
            .withCorrelationId("4431320c-7a90-4300-b82b-73f0696ae50e"), com.azure.core.util.Context.NONE);
    }
}
