
/**
 * Samples for Operations List.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-02-01-preview/Operations_List_MinimumSet_Gen.json
     */
    /**
     * Sample code: Operations_List - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to ComputeBulkActionsManager.
     */
    public static void operationsListGeneratedByMinimumSetRule(
        com.azure.resourcemanager.computebulkactions.ComputeBulkActionsManager manager) {
        manager.operations().list(com.azure.core.util.Context.NONE);
    }
}
