
/**
 * Samples for CryptoCertificates ListByFirmware.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-08-02/CryptoCertificates_ListByFirmware_MaximumSet_Gen.json
     */
    /**
     * Sample code: CryptoCertificates_ListByFirmware_MaximumSet_Gen - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to IoTFirmwareDefenseManager.
     */
    public static void cryptoCertificatesListByFirmwareMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.iotfirmwaredefense.IoTFirmwareDefenseManager manager) {
        manager.cryptoCertificates().listByFirmware("rgiotfirmwaredefense", "exampleWorkspaceName",
            "00000000-0000-0000-0000-000000000000", com.azure.core.util.Context.NONE);
    }
}
