
/**
 * Samples for Cves ListByFirmware.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-08-02/Cves_ListByFirmware_MaximumSet_Gen.json
     */
    /**
     * Sample code: Cves_ListByFirmware_MaximumSet_Gen - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to IoTFirmwareDefenseManager.
     */
    public static void cvesListByFirmwareMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.iotfirmwaredefense.IoTFirmwareDefenseManager manager) {
        manager.cves().listByFirmware("rgiotfirmwaredefense", "exampleWorkspaceName",
            "00000000-0000-0000-0000-000000000000", com.azure.core.util.Context.NONE);
    }
}
