
import com.azure.resourcemanager.iotfirmwaredefense.models.Status;
import com.azure.resourcemanager.iotfirmwaredefense.models.StatusMessage;
import java.util.Arrays;

/**
 * Samples for Firmwares Create.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-08-02/Firmwares_Create_MaximumSet_Gen.json
     */
    /**
     * Sample code: Firmwares_Create_MaximumSet_Gen - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to IoTFirmwareDefenseManager.
     */
    public static void firmwaresCreateMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.iotfirmwaredefense.IoTFirmwareDefenseManager manager) {
        manager.firmwares().define("00000000-0000-0000-0000-000000000000")
            .withExistingWorkspace("rgiotfirmwaredefense", "exampleWorkspaceName")
            .withFileName("NameOfFirmwareFile.bin").withVendor("ExampleVendorName").withModel("ExampleModelOfDevice")
            .withVersion("1.0.0").withDescription("User provided description of the firmware.").withFileSize(30L)
            .withStatus(Status.PENDING)
            .withStatusMessages(
                Arrays.asList(new StatusMessage().withErrorCode(200L).withMessage("What would this message say?")))
            .create();
    }
}
