
/**
 * Samples for Firmwares Delete.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-08-02/Firmwares_Delete_MaximumSet_Gen.json
     */
    /**
     * Sample code: Firmwares_Delete_MaximumSet_Gen - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to IoTFirmwareDefenseManager.
     */
    public static void firmwaresDeleteMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.iotfirmwaredefense.IoTFirmwareDefenseManager manager) {
        manager.firmwares().deleteWithResponse("rgiotfirmwaredefense", "exampleWorkspaceName",
            "00000000-0000-0000-0000-000000000000", com.azure.core.util.Context.NONE);
    }
}
