
/**
 * Samples for Operations List.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-08-02/Operations_List_MinimumSet_Gen.json
     */
    /**
     * Sample code: Operations_List_MaximumSet_Gen - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to IoTFirmwareDefenseManager.
     */
    public static void operationsListMaximumSetGenGeneratedByMinimumSetRule(
        com.azure.resourcemanager.iotfirmwaredefense.IoTFirmwareDefenseManager manager) {
        manager.operations().list(com.azure.core.util.Context.NONE);
    }
}
