
import com.azure.resourcemanager.iotfirmwaredefense.models.SummaryType;

/**
 * Samples for Summaries Get.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-08-02/Summaries_Get_MaximumSet_Gen.json
     */
    /**
     * Sample code: Summaries_Get_MaximumSet_Gen - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to IoTFirmwareDefenseManager.
     */
    public static void summariesGetMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.iotfirmwaredefense.IoTFirmwareDefenseManager manager) {
        manager.summaries().getWithResponse("rgiotfirmwaredefense", "exampleWorkspaceName",
            "00000000-0000-0000-0000-000000000000", SummaryType.FIRMWARE, com.azure.core.util.Context.NONE);
    }
}
