
/**
 * Samples for UsageMetrics ListByWorkspace.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-08-02/UsageMetrics_ListByWorkspace_MaximumSet_Gen.json
     */
    /**
     * Sample code: UsageMetrics_ListByWorkspace - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to IoTFirmwareDefenseManager.
     */
    public static void usageMetricsListByWorkspaceGeneratedByMaximumSetRule(
        com.azure.resourcemanager.iotfirmwaredefense.IoTFirmwareDefenseManager manager) {
        manager.usageMetrics().listByWorkspace("rgiotfirmwaredefense", "exampleWorkspaceName",
            com.azure.core.util.Context.NONE);
    }
}
