
import com.azure.resourcemanager.iotfirmwaredefense.models.GenerateUploadUrlRequest;

/**
 * Samples for Workspaces GenerateUploadUrl.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-08-02/Workspaces_GenerateUploadUrl_MaximumSet_Gen.json
     */
    /**
     * Sample code: Workspaces_GenerateUploadUrl_MaximumSet_Gen - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to IoTFirmwareDefenseManager.
     */
    public static void workspacesGenerateUploadUrlMaximumSetGenGeneratedByMaximumSetRule(
        com.azure.resourcemanager.iotfirmwaredefense.IoTFirmwareDefenseManager manager) {
        manager.workspaces().generateUploadUrlWithResponse("rgiotfirmwaredefense", "exampleWorkspaceName",
            new GenerateUploadUrlRequest().withFirmwareId("00000000-0000-0000-0000-000000000000"),
            com.azure.core.util.Context.NONE);
    }
}
