
/**
 * Samples for DataTypes Create.
 */
public final class Main {
    /*
     * x-ms-original-file:
     * specification/networkanalytics/resource-manager/Microsoft.NetworkAnalytics/stable/2023-11-15/examples/
     * DataTypes_Create_MinimumSet_Gen.json
     */
    /**
     * Sample code: DataTypes_Create_MaximumSet_Gen - generated by [MinimumSet] rule_MinimumSet_Gen.
     * 
     * @param manager Entry point to NetworkAnalyticsManager.
     */
    public static void dataTypesCreateMaximumSetGenGeneratedByMinimumSetRuleMinimumSetGen(
        com.azure.resourcemanager.networkanalytics.NetworkAnalyticsManager manager) {
        manager.dataTypes().define("datatypename").withExistingDataProduct("aoiresourceGroupName", "dataproduct01")
            .create();
    }
}
