
/**
 * Samples for DataProducts GetByResourceGroup.
 */
public final class Main {
    /*
     * x-ms-original-file:
     * specification/networkanalytics/resource-manager/Microsoft.NetworkAnalytics/stable/2023-11-15/examples/
     * DataProducts_Get_MinimumSet_Gen.json
     */
    /**
     * Sample code: DataProducts_Get_MaximumSet_Gen - generated by [MinimumSet] rule_MinimumSet_Gen.
     * 
     * @param manager Entry point to NetworkAnalyticsManager.
     */
    public static void dataProductsGetMaximumSetGenGeneratedByMinimumSetRuleMinimumSetGen(
        com.azure.resourcemanager.networkanalytics.NetworkAnalyticsManager manager) {
        manager.dataProducts().getByResourceGroupWithResponse("aoiresourceGroupName", "dataproduct01",
            com.azure.core.util.Context.NONE);
    }
}
