
import com.azure.resourcemanager.networkanalytics.models.DataType;

/**
 * Samples for DataTypes Update.
 */
public final class Main {
    /*
     * x-ms-original-file:
     * specification/networkanalytics/resource-manager/Microsoft.NetworkAnalytics/stable/2023-11-15/examples/
     * DataTypes_Update_MinimumSet_Gen.json
     */
    /**
     * Sample code: DataTypes_Update_MaximumSet_Gen - generated by [MinimumSet] rule_MinimumSet_Gen.
     * 
     * @param manager Entry point to NetworkAnalyticsManager.
     */
    public static void dataTypesUpdateMaximumSetGenGeneratedByMinimumSetRuleMinimumSetGen(
        com.azure.resourcemanager.networkanalytics.NetworkAnalyticsManager manager) {
        DataType resource = manager.dataTypes()
            .getWithResponse("aoiresourceGroupName", "dataproduct01", "datatypename", com.azure.core.util.Context.NONE)
            .getValue();
        resource.update().apply();
    }
}
