
import com.azure.resourcemanager.networkanalytics.models.ContainerSaS;
import java.time.OffsetDateTime;

/**
 * Samples for DataTypes GenerateStorageContainerSasToken.
 */
public final class Main {
    /*
     * x-ms-original-file:
     * specification/networkanalytics/resource-manager/Microsoft.NetworkAnalytics/stable/2023-11-15/examples/
     * DataTypes_GenerateStorageContainerSasToken_MinimumSet_Gen.json
     */
    /**
     * Sample code: DataTypes_GenerateStorageContainerSasToken_MaximumSet_Gen - generated by [MinimumSet]
     * rule_MinimumSet_Gen.
     * 
     * @param manager Entry point to NetworkAnalyticsManager.
     */
    public static void dataTypesGenerateStorageContainerSasTokenMaximumSetGenGeneratedByMinimumSetRuleMinimumSetGen(
        com.azure.resourcemanager.networkanalytics.NetworkAnalyticsManager manager) {
        manager.dataTypes().generateStorageContainerSasTokenWithResponse("aoiresourceGroupName", "dataproduct01",
            "datatypename",
            new ContainerSaS().withStartTimestamp(OffsetDateTime.parse("2023-08-24T05:35:16.887Z"))
                .withExpiryTimestamp(OffsetDateTime.parse("2023-08-24T05:35:16.887Z")).withIpAddress("1.1.1.1"),
            com.azure.core.util.Context.NONE);
    }
}
