
/**
 * Samples for DeidServices GetByResourceGroup.
 */
public final class Main {
    /*
     * x-ms-original-file: 2024-09-20/DeidServices_Get_MaximumSet_Gen.json
     */
    /**
     * Sample code: DeidServices_Get - generated by [MaximumSet] rule. [stable].
     * 
     * @param manager Entry point to HealthDataAIServicesManager.
     */
    public static void deidServicesGetGeneratedByMaximumSetRuleStable(
        com.azure.resourcemanager.healthdataaiservices.HealthDataAIServicesManager manager) {
        manager.deidServices().getByResourceGroupWithResponse("rgopenapi", "deidTest",
            com.azure.core.util.Context.NONE);
    }
}
