
/**
 * Samples for DeidServices Delete.
 */
public final class Main {
    /*
     * x-ms-original-file: 2024-09-20/DeidServices_Delete_MaximumSet_Gen.json
     */
    /**
     * Sample code: DeidServices_Delete - generated by [MaximumSet] rule. [stable].
     * 
     * @param manager Entry point to HealthDataAIServicesManager.
     */
    public static void deidServicesDeleteGeneratedByMaximumSetRuleStable(
        com.azure.resourcemanager.healthdataaiservices.HealthDataAIServicesManager manager) {
        manager.deidServices().delete("rgopenapi", "deidTest", com.azure.core.util.Context.NONE);
    }
}
