
/**
 * Samples for Operations List.
 */
public final class Main {
    /*
     * x-ms-original-file: 2024-09-20/Operations_List_MaximumSet_Gen.json
     */
    /**
     * Sample code: Operations_List_MaximumSet - generated by [MaximumSet] rule. [stable].
     * 
     * @param manager Entry point to HealthDataAIServicesManager.
     */
    public static void operationsListMaximumSetGeneratedByMaximumSetRuleStable(
        com.azure.resourcemanager.healthdataaiservices.HealthDataAIServicesManager manager) {
        manager.operations().list(com.azure.core.util.Context.NONE);
    }
}
