
/**
 * Samples for Operations List.
 */
public final class Main {
    /*
     * x-ms-original-file: 2024-09-20/Operations_List_MinimumSet_Gen.json
     */
    /**
     * Sample code: Operations_List_MinimumSet - generated by [MinimumSet] rule. [stable].
     * 
     * @param manager Entry point to HealthDataAIServicesManager.
     */
    public static void operationsListMinimumSetGeneratedByMinimumSetRuleStable(
        com.azure.resourcemanager.healthdataaiservices.HealthDataAIServicesManager manager) {
        manager.operations().list(com.azure.core.util.Context.NONE);
    }
}
