
import com.azure.resourcemanager.healthdataaiservices.models.PrivateEndpoint;
import com.azure.resourcemanager.healthdataaiservices.models.PrivateEndpointConnectionProperties;
import com.azure.resourcemanager.healthdataaiservices.models.PrivateEndpointServiceConnectionStatus;
import com.azure.resourcemanager.healthdataaiservices.models.PrivateLinkServiceConnectionState;

/**
 * Samples for PrivateEndpointConnections Create.
 */
public final class Main {
    /*
     * x-ms-original-file: 2024-09-20/PrivateEndpointConnections_Create_MaximumSet_Gen.json
     */
    /**
     * Sample code: PrivateEndpointConnections_Create - generated by [MaximumSet] rule. [stable].
     * 
     * @param manager Entry point to HealthDataAIServicesManager.
     */
    public static void privateEndpointConnectionsCreateGeneratedByMaximumSetRuleStable(
        com.azure.resourcemanager.healthdataaiservices.HealthDataAIServicesManager manager) {
        manager.privateEndpointConnections().define("kgwgrrpabvrsrrvpcgcnfmyfgyrl")
            .withExistingDeidService("rgopenapi", "deidTest")
            .withProperties(
                new PrivateEndpointConnectionProperties().withPrivateEndpoint(new PrivateEndpoint())
                    .withPrivateLinkServiceConnectionState(new PrivateLinkServiceConnectionState()
                        .withStatus(PrivateEndpointServiceConnectionStatus.PENDING).withDescription("xr")
                        .withActionsRequired("ulb")))
            .create();
    }
}
