
/**
 * Samples for PrivateLinks ListByDeidService.
 */
public final class Main {
    /*
     * x-ms-original-file: 2024-09-20/PrivateLinks_ListByDeidService_MaximumSet_Gen.json
     */
    /**
     * Sample code: PrivateLinks_ListByDeidService - generated by [MaximumSet] rule. [stable].
     * 
     * @param manager Entry point to HealthDataAIServicesManager.
     */
    public static void privateLinksListByDeidServiceGeneratedByMaximumSetRuleStable(
        com.azure.resourcemanager.healthdataaiservices.HealthDataAIServicesManager manager) {
        manager.privateLinks().listByDeidService("rgopenapi", "deidTest", com.azure.core.util.Context.NONE);
    }
}
