
/**
 * Samples for PrivateEndpointConnections Get.
 */
public final class Main {
    /*
     * x-ms-original-file: 2024-09-20/PrivateEndpointConnections_Get_MaximumSet_Gen.json
     */
    /**
     * Sample code: PrivateEndpointConnections_Get - generated by [MaximumSet] rule. [stable].
     * 
     * @param manager Entry point to HealthDataAIServicesManager.
     */
    public static void privateEndpointConnectionsGetGeneratedByMaximumSetRuleStable(
        com.azure.resourcemanager.healthdataaiservices.HealthDataAIServicesManager manager) {
        manager.privateEndpointConnections().getWithResponse("rgopenapi", "deidTest", "kgwgrrpabvrsrrvpcgcnfmyfgyrl",
            com.azure.core.util.Context.NONE);
    }
}
