package armmigrate_test

import (
	"context"
	"log"

	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/migrate/armmigrate"
)

// Generated from example definition: https://github.com/Azure/azure-rest-api-specs/blob/163e27c0ca7570bc39e00a46f255740d9b3ba3cb/specification/migrate/resource-manager/Microsoft.Migrate/stable/2019-10-01/examples/AssessmentOptions_List.json
func ExampleProjectsClient_NewAssessmentOptionsListPager() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
	}
	ctx := context.Background()
	clientFactory, err := armmigrate.NewClientFactory("<subscription-id>", cred, nil)
	if err != nil {
		log.Fatalf("failed to create client: %v", err)
	}
	pager := clientFactory.NewProjectsClient().NewAssessmentOptionsListPager("abgoyal-westEurope", "abgoyalWEselfhostb72bproject", nil)
	for pager.More() {
		page, err := pager.NextPage(ctx)
		if err != nil {
			log.Fatalf("failed to advance page: %v", err)
		}
		for _, v := range page.Value {
			// You could use page here. We use blank identifier for just demo purposes.
			_ = v
		}
		// If the HTTP response code is 200 as defined in example definition, your page structure would look as follows. Please pay attention that all the values in the output are fake values for just demo purposes.
		// page.AssessmentOptionsResultList = armmigrate.AssessmentOptionsResultList{
		// 	Value: []*armmigrate.AssessmentOptions{
		// 		{
		// 			Name: to.Ptr("default"),
		// 			ID: to.Ptr("/subscriptions/5cbd71ba-5a65-4f0c-aea2-33dadde87b4e/resourceGroups/shsinglarg/providers/Microsoft.Migrate/assessmentprojects/shProject/assessmentOptions/default"),
		// 			Properties: &armmigrate.AssessmentOptionsProperties{
		// 				ReservedInstanceSupportedCurrencies: []*string{
		// 					to.Ptr("USD"),
		// 					to.Ptr("DKK"),
		// 					to.Ptr("CAD"),
		// 					to.Ptr("JPY"),
		// 					to.Ptr("KRW"),
		// 					to.Ptr("NZD"),
		// 					to.Ptr("NOK"),
		// 					to.Ptr("RUB"),
		// 					to.Ptr("SEK"),
		// 					to.Ptr("GBP"),
		// 					to.Ptr("INR"),
		// 					to.Ptr("BRL"),
		// 					to.Ptr("TWD"),
		// 					to.Ptr("EUR"),
		// 					to.Ptr("CHF"),
		// 					to.Ptr("AUD")},
		// 					ReservedInstanceSupportedLocations: []*string{
		// 						to.Ptr("EastAsia"),
		// 						to.Ptr("SoutheastAsia"),
		// 						to.Ptr("AustraliaEast"),
		// 						to.Ptr("AustraliaSoutheast"),
		// 						to.Ptr("BrazilSouth"),
		// 						to.Ptr("CanadaCentral"),
		// 						to.Ptr("CanadaEast"),
		// 						to.Ptr("WestEurope"),
		// 						to.Ptr("NorthEurope"),
		// 						to.Ptr("CentralIndia"),
		// 						to.Ptr("SouthIndia"),
		// 						to.Ptr("WestIndia"),
		// 						to.Ptr("JapanEast"),
		// 						to.Ptr("JapanWest"),
		// 						to.Ptr("KoreaCentral"),
		// 						to.Ptr("KoreaSouth"),
		// 						to.Ptr("UkWest"),
		// 						to.Ptr("UkSouth"),
		// 						to.Ptr("NorthCentralUs"),
		// 						to.Ptr("EastUs"),
		// 						to.Ptr("WestUs2"),
		// 						to.Ptr("SouthCentralUs"),
		// 						to.Ptr("CentralUs"),
		// 						to.Ptr("EastUs2"),
		// 						to.Ptr("WestUs"),
		// 						to.Ptr("WestCentralUs")},
		// 						ReservedInstanceSupportedOffers: []*string{
		// 							to.Ptr("MSAZR0003P")},
		// 							ReservedInstanceVMFamilies: []*string{
		// 								to.Ptr("Dv2_series"),
		// 								to.Ptr("F_series"),
		// 								to.Ptr("Dv3_series"),
		// 								to.Ptr("DS_series"),
		// 								to.Ptr("DSv2_series"),
		// 								to.Ptr("Fs_series"),
		// 								to.Ptr("Dsv3_series"),
		// 								to.Ptr("Ev3_series"),
		// 								to.Ptr("Esv3_series"),
		// 								to.Ptr("D_series"),
		// 								to.Ptr("Fsv2_series"),
		// 								to.Ptr("M_series"),
		// 								to.Ptr("Ls_series"),
		// 								to.Ptr("H_series")},
		// 								VMFamilies: []*armmigrate.VMFamily{
		// 									{
		// 										Category: []*string{
		// 											to.Ptr("GeneralPurpose")},
		// 											FamilyName: to.Ptr("Standard_A0_A7"),
		// 											TargetLocations: []*string{
		// 												to.Ptr("EastAsia"),
		// 												to.Ptr("SoutheastAsia"),
		// 												to.Ptr("AustraliaEast"),
		// 												to.Ptr("AustraliaSoutheast"),
		// 												to.Ptr("BrazilSouth"),
		// 												to.Ptr("CanadaCentral"),
		// 												to.Ptr("CanadaEast"),
		// 												to.Ptr("WestEurope"),
		// 												to.Ptr("NorthEurope"),
		// 												to.Ptr("CentralIndia"),
		// 												to.Ptr("SouthIndia"),
		// 												to.Ptr("WestIndia"),
		// 												to.Ptr("JapanEast"),
		// 												to.Ptr("JapanWest"),
		// 												to.Ptr("KoreaCentral"),
		// 												to.Ptr("KoreaSouth"),
		// 												to.Ptr("UkWest"),
		// 												to.Ptr("UkSouth"),
		// 												to.Ptr("NorthCentralUs"),
		// 												to.Ptr("EastUs"),
		// 												to.Ptr("WestUs2"),
		// 												to.Ptr("SouthCentralUs"),
		// 												to.Ptr("CentralUs"),
		// 												to.Ptr("EastUs2"),
		// 												to.Ptr("WestUs"),
		// 												to.Ptr("WestCentralUs"),
		// 												to.Ptr("FranceCentral"),
		// 												to.Ptr("GermanyNortheast"),
		// 												to.Ptr("GermanyCentral"),
		// 												to.Ptr("USGovTexas"),
		// 												to.Ptr("USGovArizona"),
		// 												to.Ptr("USGovIowa"),
		// 												to.Ptr("USGovVirginia"),
		// 												to.Ptr("USDoDCentral"),
		// 												to.Ptr("USDoDEast"),
		// 												to.Ptr("ChinaNorth"),
		// 												to.Ptr("ChinaEast")},
		// 											},
		// 											{
		// 												Category: []*string{
		// 													to.Ptr("GeneralPurpose")},
		// 													FamilyName: to.Ptr("Basic_A0_A4"),
		// 													TargetLocations: []*string{
		// 														to.Ptr("EastAsia"),
		// 														to.Ptr("SoutheastAsia"),
		// 														to.Ptr("AustraliaEast"),
		// 														to.Ptr("AustraliaSoutheast"),
		// 														to.Ptr("BrazilSouth"),
		// 														to.Ptr("CanadaCentral"),
		// 														to.Ptr("CanadaEast"),
		// 														to.Ptr("WestEurope"),
		// 														to.Ptr("NorthEurope"),
		// 														to.Ptr("CentralIndia"),
		// 														to.Ptr("SouthIndia"),
		// 														to.Ptr("WestIndia"),
		// 														to.Ptr("JapanEast"),
		// 														to.Ptr("JapanWest"),
		// 														to.Ptr("KoreaCentral"),
		// 														to.Ptr("KoreaSouth"),
		// 														to.Ptr("UkWest"),
		// 														to.Ptr("UkSouth"),
		// 														to.Ptr("NorthCentralUs"),
		// 														to.Ptr("EastUs"),
		// 														to.Ptr("WestUs2"),
		// 														to.Ptr("SouthCentralUs"),
		// 														to.Ptr("CentralUs"),
		// 														to.Ptr("EastUs2"),
		// 														to.Ptr("WestUs"),
		// 														to.Ptr("WestCentralUs"),
		// 														to.Ptr("FranceCentral"),
		// 														to.Ptr("GermanyNortheast"),
		// 														to.Ptr("GermanyCentral"),
		// 														to.Ptr("USGovTexas"),
		// 														to.Ptr("USGovArizona"),
		// 														to.Ptr("USGovIowa"),
		// 														to.Ptr("USGovVirginia"),
		// 														to.Ptr("USDoDCentral"),
		// 														to.Ptr("USDoDEast"),
		// 														to.Ptr("ChinaNorth"),
		// 														to.Ptr("ChinaEast")},
		// 													},
		// 													{
		// 														Category: []*string{
		// 															to.Ptr("GeneralPurpose"),
		// 															to.Ptr("MemoryOptimized")},
		// 															FamilyName: to.Ptr("Dv2_series"),
		// 															TargetLocations: []*string{
		// 																to.Ptr("EastAsia"),
		// 																to.Ptr("SoutheastAsia"),
		// 																to.Ptr("AustraliaEast"),
		// 																to.Ptr("AustraliaSoutheast"),
		// 																to.Ptr("BrazilSouth"),
		// 																to.Ptr("CanadaCentral"),
		// 																to.Ptr("CanadaEast"),
		// 																to.Ptr("WestEurope"),
		// 																to.Ptr("NorthEurope"),
		// 																to.Ptr("CentralIndia"),
		// 																to.Ptr("SouthIndia"),
		// 																to.Ptr("WestIndia"),
		// 																to.Ptr("JapanEast"),
		// 																to.Ptr("JapanWest"),
		// 																to.Ptr("KoreaCentral"),
		// 																to.Ptr("KoreaSouth"),
		// 																to.Ptr("UkWest"),
		// 																to.Ptr("UkSouth"),
		// 																to.Ptr("NorthCentralUs"),
		// 																to.Ptr("EastUs"),
		// 																to.Ptr("WestUs2"),
		// 																to.Ptr("SouthCentralUs"),
		// 																to.Ptr("CentralUs"),
		// 																to.Ptr("EastUs2"),
		// 																to.Ptr("WestUs"),
		// 																to.Ptr("WestCentralUs"),
		// 																to.Ptr("FranceCentral"),
		// 																to.Ptr("GermanyNortheast"),
		// 																to.Ptr("GermanyCentral"),
		// 																to.Ptr("USGovTexas"),
		// 																to.Ptr("USGovArizona"),
		// 																to.Ptr("USGovIowa"),
		// 																to.Ptr("USGovVirginia"),
		// 																to.Ptr("USDoDCentral"),
		// 																to.Ptr("USDoDEast"),
		// 																to.Ptr("ChinaNorth"),
		// 																to.Ptr("ChinaEast")},
		// 															},
		// 															{
		// 																Category: []*string{
		// 																	to.Ptr("ComputeOptimized")},
		// 																	FamilyName: to.Ptr("F_series"),
		// 																	TargetLocations: []*string{
		// 																		to.Ptr("EastAsia"),
		// 																		to.Ptr("SoutheastAsia"),
		// 																		to.Ptr("AustraliaEast"),
		// 																		to.Ptr("AustraliaSoutheast"),
		// 																		to.Ptr("BrazilSouth"),
		// 																		to.Ptr("CanadaCentral"),
		// 																		to.Ptr("CanadaEast"),
		// 																		to.Ptr("WestEurope"),
		// 																		to.Ptr("NorthEurope"),
		// 																		to.Ptr("CentralIndia"),
		// 																		to.Ptr("SouthIndia"),
		// 																		to.Ptr("WestIndia"),
		// 																		to.Ptr("JapanEast"),
		// 																		to.Ptr("JapanWest"),
		// 																		to.Ptr("KoreaCentral"),
		// 																		to.Ptr("KoreaSouth"),
		// 																		to.Ptr("UkWest"),
		// 																		to.Ptr("UkSouth"),
		// 																		to.Ptr("NorthCentralUs"),
		// 																		to.Ptr("EastUs"),
		// 																		to.Ptr("WestUs2"),
		// 																		to.Ptr("SouthCentralUs"),
		// 																		to.Ptr("CentralUs"),
		// 																		to.Ptr("EastUs2"),
		// 																		to.Ptr("WestUs"),
		// 																		to.Ptr("WestCentralUs"),
		// 																		to.Ptr("FranceCentral"),
		// 																		to.Ptr("GermanyNortheast"),
		// 																		to.Ptr("GermanyCentral"),
		// 																		to.Ptr("USGovTexas"),
		// 																		to.Ptr("USGovArizona"),
		// 																		to.Ptr("USGovIowa"),
		// 																		to.Ptr("USGovVirginia"),
		// 																		to.Ptr("USDoDCentral"),
		// 																		to.Ptr("USDoDEast"),
		// 																		to.Ptr("ChinaNorth"),
		// 																		to.Ptr("ChinaEast")},
		// 																	},
		// 																	{
		// 																		Category: []*string{
		// 																			to.Ptr("GeneralPurpose")},
		// 																			FamilyName: to.Ptr("Av2_series"),
		// 																			TargetLocations: []*string{
		// 																				to.Ptr("EastAsia"),
		// 																				to.Ptr("SoutheastAsia"),
		// 																				to.Ptr("AustraliaEast"),
		// 																				to.Ptr("AustraliaSoutheast"),
		// 																				to.Ptr("BrazilSouth"),
		// 																				to.Ptr("CanadaCentral"),
		// 																				to.Ptr("CanadaEast"),
		// 																				to.Ptr("WestEurope"),
		// 																				to.Ptr("NorthEurope"),
		// 																				to.Ptr("CentralIndia"),
		// 																				to.Ptr("SouthIndia"),
		// 																				to.Ptr("WestIndia"),
		// 																				to.Ptr("JapanEast"),
		// 																				to.Ptr("JapanWest"),
		// 																				to.Ptr("KoreaCentral"),
		// 																				to.Ptr("KoreaSouth"),
		// 																				to.Ptr("UkWest"),
		// 																				to.Ptr("UkSouth"),
		// 																				to.Ptr("NorthCentralUs"),
		// 																				to.Ptr("EastUs"),
		// 																				to.Ptr("WestUs2"),
		// 																				to.Ptr("SouthCentralUs"),
		// 																				to.Ptr("CentralUs"),
		// 																				to.Ptr("EastUs2"),
		// 																				to.Ptr("WestUs"),
		// 																				to.Ptr("WestCentralUs"),
		// 																				to.Ptr("FranceCentral"),
		// 																				to.Ptr("GermanyNortheast"),
		// 																				to.Ptr("GermanyCentral"),
		// 																				to.Ptr("USGovTexas"),
		// 																				to.Ptr("USGovArizona"),
		// 																				to.Ptr("USGovIowa"),
		// 																				to.Ptr("USGovVirginia"),
		// 																				to.Ptr("USDoDCentral"),
		// 																				to.Ptr("USDoDEast"),
		// 																				to.Ptr("ChinaNorth"),
		// 																				to.Ptr("ChinaEast")},
		// 																			},
		// 																			{
		// 																				Category: []*string{
		// 																					to.Ptr("GeneralPurpose")},
		// 																					FamilyName: to.Ptr("Dv3_series"),
		// 																					TargetLocations: []*string{
		// 																						to.Ptr("EastAsia"),
		// 																						to.Ptr("SoutheastAsia"),
		// 																						to.Ptr("AustraliaEast"),
		// 																						to.Ptr("AustraliaSoutheast"),
		// 																						to.Ptr("BrazilSouth"),
		// 																						to.Ptr("CanadaCentral"),
		// 																						to.Ptr("CanadaEast"),
		// 																						to.Ptr("WestEurope"),
		// 																						to.Ptr("NorthEurope"),
		// 																						to.Ptr("CentralIndia"),
		// 																						to.Ptr("SouthIndia"),
		// 																						to.Ptr("WestIndia"),
		// 																						to.Ptr("JapanEast"),
		// 																						to.Ptr("JapanWest"),
		// 																						to.Ptr("KoreaCentral"),
		// 																						to.Ptr("KoreaSouth"),
		// 																						to.Ptr("UkWest"),
		// 																						to.Ptr("UkSouth"),
		// 																						to.Ptr("NorthCentralUs"),
		// 																						to.Ptr("EastUs"),
		// 																						to.Ptr("WestUs2"),
		// 																						to.Ptr("SouthCentralUs"),
		// 																						to.Ptr("CentralUs"),
		// 																						to.Ptr("EastUs2"),
		// 																						to.Ptr("WestUs"),
		// 																						to.Ptr("WestCentralUs"),
		// 																						to.Ptr("FranceCentral"),
		// 																						to.Ptr("GermanyNortheast"),
		// 																						to.Ptr("GermanyCentral"),
		// 																						to.Ptr("USGovTexas"),
		// 																						to.Ptr("USGovArizona"),
		// 																						to.Ptr("USGovIowa"),
		// 																						to.Ptr("USGovVirginia"),
		// 																						to.Ptr("ChinaEast")},
		// 																					},
		// 																					{
		// 																						Category: []*string{
		// 																							to.Ptr("GeneralPurpose"),
		// 																							to.Ptr("MemoryOptimized"),
		// 																							to.Ptr("SupportsPremiumStorage")},
		// 																							FamilyName: to.Ptr("DS_series"),
		// 																							TargetLocations: []*string{
		// 																								to.Ptr("EastAsia"),
		// 																								to.Ptr("SoutheastAsia"),
		// 																								to.Ptr("AustraliaEast"),
		// 																								to.Ptr("AustraliaSoutheast"),
		// 																								to.Ptr("BrazilSouth"),
		// 																								to.Ptr("WestEurope"),
		// 																								to.Ptr("NorthEurope"),
		// 																								to.Ptr("JapanEast"),
		// 																								to.Ptr("JapanWest"),
		// 																								to.Ptr("EastUs"),
		// 																								to.Ptr("SouthCentralUs"),
		// 																								to.Ptr("CentralUs"),
		// 																								to.Ptr("EastUs2"),
		// 																								to.Ptr("WestUs"),
		// 																								to.Ptr("USGovVirginia"),
		// 																								to.Ptr("ChinaNorth"),
		// 																								to.Ptr("ChinaEast")},
		// 																							},
		// 																							{
		// 																								Category: []*string{
		// 																									to.Ptr("GeneralPurpose"),
		// 																									to.Ptr("MemoryOptimized"),
		// 																									to.Ptr("SupportsPremiumStorage")},
		// 																									FamilyName: to.Ptr("DSv2_series"),
		// 																									TargetLocations: []*string{
		// 																										to.Ptr("EastAsia"),
		// 																										to.Ptr("SoutheastAsia"),
		// 																										to.Ptr("AustraliaEast"),
		// 																										to.Ptr("AustraliaSoutheast"),
		// 																										to.Ptr("BrazilSouth"),
		// 																										to.Ptr("CanadaCentral"),
		// 																										to.Ptr("CanadaEast"),
		// 																										to.Ptr("WestEurope"),
		// 																										to.Ptr("NorthEurope"),
		// 																										to.Ptr("CentralIndia"),
		// 																										to.Ptr("SouthIndia"),
		// 																										to.Ptr("WestIndia"),
		// 																										to.Ptr("JapanEast"),
		// 																										to.Ptr("JapanWest"),
		// 																										to.Ptr("KoreaCentral"),
		// 																										to.Ptr("KoreaSouth"),
		// 																										to.Ptr("UkWest"),
		// 																										to.Ptr("UkSouth"),
		// 																										to.Ptr("NorthCentralUs"),
		// 																										to.Ptr("EastUs"),
		// 																										to.Ptr("WestUs2"),
		// 																										to.Ptr("SouthCentralUs"),
		// 																										to.Ptr("CentralUs"),
		// 																										to.Ptr("EastUs2"),
		// 																										to.Ptr("WestUs"),
		// 																										to.Ptr("WestCentralUs"),
		// 																										to.Ptr("FranceCentral"),
		// 																										to.Ptr("GermanyNortheast"),
		// 																										to.Ptr("GermanyCentral"),
		// 																										to.Ptr("USGovTexas"),
		// 																										to.Ptr("USGovArizona"),
		// 																										to.Ptr("USGovVirginia"),
		// 																										to.Ptr("USDoDCentral"),
		// 																										to.Ptr("USDoDEast"),
		// 																										to.Ptr("ChinaNorth"),
		// 																										to.Ptr("ChinaEast")},
		// 																									},
		// 																									{
		// 																										Category: []*string{
		// 																											to.Ptr("ComputeOptimized"),
		// 																											to.Ptr("SupportsPremiumStorage")},
		// 																											FamilyName: to.Ptr("Fs_series"),
		// 																											TargetLocations: []*string{
		// 																												to.Ptr("EastAsia"),
		// 																												to.Ptr("SoutheastAsia"),
		// 																												to.Ptr("AustraliaEast"),
		// 																												to.Ptr("AustraliaSoutheast"),
		// 																												to.Ptr("BrazilSouth"),
		// 																												to.Ptr("CanadaCentral"),
		// 																												to.Ptr("CanadaEast"),
		// 																												to.Ptr("WestEurope"),
		// 																												to.Ptr("NorthEurope"),
		// 																												to.Ptr("CentralIndia"),
		// 																												to.Ptr("SouthIndia"),
		// 																												to.Ptr("WestIndia"),
		// 																												to.Ptr("JapanEast"),
		// 																												to.Ptr("JapanWest"),
		// 																												to.Ptr("KoreaCentral"),
		// 																												to.Ptr("KoreaSouth"),
		// 																												to.Ptr("UkWest"),
		// 																												to.Ptr("UkSouth"),
		// 																												to.Ptr("NorthCentralUs"),
		// 																												to.Ptr("EastUs"),
		// 																												to.Ptr("WestUs2"),
		// 																												to.Ptr("SouthCentralUs"),
		// 																												to.Ptr("CentralUs"),
		// 																												to.Ptr("EastUs2"),
		// 																												to.Ptr("WestUs"),
		// 																												to.Ptr("WestCentralUs"),
		// 																												to.Ptr("FranceCentral"),
		// 																												to.Ptr("GermanyNortheast"),
		// 																												to.Ptr("GermanyCentral"),
		// 																												to.Ptr("USGovTexas"),
		// 																												to.Ptr("USGovArizona"),
		// 																												to.Ptr("USGovVirginia"),
		// 																												to.Ptr("USDoDCentral"),
		// 																												to.Ptr("USDoDEast"),
		// 																												to.Ptr("ChinaNorth"),
		// 																												to.Ptr("ChinaEast")},
		// 																											},
		// 																											{
		// 																												Category: []*string{
		// 																													to.Ptr("GeneralPurpose"),
		// 																													to.Ptr("SupportsPremiumStorage")},
		// 																													FamilyName: to.Ptr("Dsv3_series"),
		// 																													TargetLocations: []*string{
		// 																														to.Ptr("EastAsia"),
		// 																														to.Ptr("SoutheastAsia"),
		// 																														to.Ptr("AustraliaEast"),
		// 																														to.Ptr("AustraliaSoutheast"),
		// 																														to.Ptr("BrazilSouth"),
		// 																														to.Ptr("CanadaCentral"),
		// 																														to.Ptr("CanadaEast"),
		// 																														to.Ptr("WestEurope"),
		// 																														to.Ptr("NorthEurope"),
		// 																														to.Ptr("CentralIndia"),
		// 																														to.Ptr("SouthIndia"),
		// 																														to.Ptr("WestIndia"),
		// 																														to.Ptr("JapanEast"),
		// 																														to.Ptr("JapanWest"),
		// 																														to.Ptr("KoreaCentral"),
		// 																														to.Ptr("KoreaSouth"),
		// 																														to.Ptr("UkWest"),
		// 																														to.Ptr("UkSouth"),
		// 																														to.Ptr("NorthCentralUs"),
		// 																														to.Ptr("EastUs"),
		// 																														to.Ptr("WestUs2"),
		// 																														to.Ptr("SouthCentralUs"),
		// 																														to.Ptr("CentralUs"),
		// 																														to.Ptr("EastUs2"),
		// 																														to.Ptr("WestUs"),
		// 																														to.Ptr("WestCentralUs"),
		// 																														to.Ptr("FranceCentral"),
		// 																														to.Ptr("GermanyNortheast"),
		// 																														to.Ptr("GermanyCentral"),
		// 																														to.Ptr("USGovTexas"),
		// 																														to.Ptr("USGovArizona"),
		// 																														to.Ptr("USGovVirginia")},
		// 																													},
		// 																													{
		// 																														Category: []*string{
		// 																															to.Ptr("MemoryOptimized")},
		// 																															FamilyName: to.Ptr("Ev3_series"),
		// 																															TargetLocations: []*string{
		// 																																to.Ptr("EastAsia"),
		// 																																to.Ptr("SoutheastAsia"),
		// 																																to.Ptr("AustraliaEast"),
		// 																																to.Ptr("AustraliaSoutheast"),
		// 																																to.Ptr("BrazilSouth"),
		// 																																to.Ptr("CanadaCentral"),
		// 																																to.Ptr("CanadaEast"),
		// 																																to.Ptr("WestEurope"),
		// 																																to.Ptr("NorthEurope"),
		// 																																to.Ptr("CentralIndia"),
		// 																																to.Ptr("SouthIndia"),
		// 																																to.Ptr("WestIndia"),
		// 																																to.Ptr("JapanEast"),
		// 																																to.Ptr("JapanWest"),
		// 																																to.Ptr("KoreaCentral"),
		// 																																to.Ptr("KoreaSouth"),
		// 																																to.Ptr("UkWest"),
		// 																																to.Ptr("UkSouth"),
		// 																																to.Ptr("NorthCentralUs"),
		// 																																to.Ptr("EastUs"),
		// 																																to.Ptr("WestUs2"),
		// 																																to.Ptr("SouthCentralUs"),
		// 																																to.Ptr("CentralUs"),
		// 																																to.Ptr("EastUs2"),
		// 																																to.Ptr("WestUs"),
		// 																																to.Ptr("WestCentralUs"),
		// 																																to.Ptr("FranceCentral"),
		// 																																to.Ptr("GermanyNortheast"),
		// 																																to.Ptr("GermanyCentral"),
		// 																																to.Ptr("USGovTexas"),
		// 																																to.Ptr("USGovArizona"),
		// 																																to.Ptr("USGovIowa"),
		// 																																to.Ptr("USGovVirginia"),
		// 																																to.Ptr("ChinaEast")},
		// 																															},
		// 																															{
		// 																																Category: []*string{
		// 																																	to.Ptr("MemoryOptimized"),
		// 																																	to.Ptr("SupportsPremiumStorage")},
		// 																																	FamilyName: to.Ptr("Esv3_series"),
		// 																																	TargetLocations: []*string{
		// 																																		to.Ptr("EastAsia"),
		// 																																		to.Ptr("SoutheastAsia"),
		// 																																		to.Ptr("AustraliaEast"),
		// 																																		to.Ptr("AustraliaSoutheast"),
		// 																																		to.Ptr("BrazilSouth"),
		// 																																		to.Ptr("CanadaCentral"),
		// 																																		to.Ptr("CanadaEast"),
		// 																																		to.Ptr("WestEurope"),
		// 																																		to.Ptr("NorthEurope"),
		// 																																		to.Ptr("CentralIndia"),
		// 																																		to.Ptr("SouthIndia"),
		// 																																		to.Ptr("WestIndia"),
		// 																																		to.Ptr("JapanEast"),
		// 																																		to.Ptr("JapanWest"),
		// 																																		to.Ptr("KoreaCentral"),
		// 																																		to.Ptr("KoreaSouth"),
		// 																																		to.Ptr("UkWest"),
		// 																																		to.Ptr("UkSouth"),
		// 																																		to.Ptr("NorthCentralUs"),
		// 																																		to.Ptr("EastUs"),
		// 																																		to.Ptr("WestUs2"),
		// 																																		to.Ptr("SouthCentralUs"),
		// 																																		to.Ptr("CentralUs"),
		// 																																		to.Ptr("EastUs2"),
		// 																																		to.Ptr("WestUs"),
		// 																																		to.Ptr("WestCentralUs"),
		// 																																		to.Ptr("FranceCentral"),
		// 																																		to.Ptr("GermanyNortheast"),
		// 																																		to.Ptr("GermanyCentral"),
		// 																																		to.Ptr("USGovTexas"),
		// 																																		to.Ptr("USGovArizona"),
		// 																																		to.Ptr("USGovVirginia")},
		// 																																	},
		// 																																	{
		// 																																		Category: []*string{
		// 																																			to.Ptr("GeneralPurpose")},
		// 																																			FamilyName: to.Ptr("D_series"),
		// 																																			TargetLocations: []*string{
		// 																																				to.Ptr("EastAsia"),
		// 																																				to.Ptr("SoutheastAsia"),
		// 																																				to.Ptr("AustraliaEast"),
		// 																																				to.Ptr("AustraliaSoutheast"),
		// 																																				to.Ptr("BrazilSouth"),
		// 																																				to.Ptr("WestEurope"),
		// 																																				to.Ptr("NorthEurope"),
		// 																																				to.Ptr("JapanEast"),
		// 																																				to.Ptr("JapanWest"),
		// 																																				to.Ptr("NorthCentralUs"),
		// 																																				to.Ptr("EastUs"),
		// 																																				to.Ptr("SouthCentralUs"),
		// 																																				to.Ptr("CentralUs"),
		// 																																				to.Ptr("EastUs2"),
		// 																																				to.Ptr("WestUs"),
		// 																																				to.Ptr("USGovVirginia"),
		// 																																				to.Ptr("ChinaNorth"),
		// 																																				to.Ptr("ChinaEast")},
		// 																																			},
		// 																																			{
		// 																																				Category: []*string{
		// 																																					to.Ptr("ComputeOptimized"),
		// 																																					to.Ptr("SupportsPremiumStorage")},
		// 																																					FamilyName: to.Ptr("Fsv2_series"),
		// 																																					TargetLocations: []*string{
		// 																																						to.Ptr("EastAsia"),
		// 																																						to.Ptr("SoutheastAsia"),
		// 																																						to.Ptr("AustraliaEast"),
		// 																																						to.Ptr("AustraliaSoutheast"),
		// 																																						to.Ptr("BrazilSouth"),
		// 																																						to.Ptr("CanadaCentral"),
		// 																																						to.Ptr("CanadaEast"),
		// 																																						to.Ptr("WestEurope"),
		// 																																						to.Ptr("NorthEurope"),
		// 																																						to.Ptr("CentralIndia"),
		// 																																						to.Ptr("SouthIndia"),
		// 																																						to.Ptr("WestIndia"),
		// 																																						to.Ptr("JapanEast"),
		// 																																						to.Ptr("JapanWest"),
		// 																																						to.Ptr("KoreaCentral"),
		// 																																						to.Ptr("KoreaSouth"),
		// 																																						to.Ptr("UkWest"),
		// 																																						to.Ptr("UkSouth"),
		// 																																						to.Ptr("NorthCentralUs"),
		// 																																						to.Ptr("EastUs"),
		// 																																						to.Ptr("WestUs2"),
		// 																																						to.Ptr("SouthCentralUs"),
		// 																																						to.Ptr("CentralUs"),
		// 																																						to.Ptr("EastUs2"),
		// 																																						to.Ptr("WestUs"),
		// 																																						to.Ptr("FranceCentral"),
		// 																																						to.Ptr("USGovArizona"),
		// 																																						to.Ptr("USGovVirginia")},
		// 																																					},
		// 																																					{
		// 																																						Category: []*string{
		// 																																							to.Ptr("MemoryOptimized"),
		// 																																							to.Ptr("SupportsPremiumStorage")},
		// 																																							FamilyName: to.Ptr("M_series"),
		// 																																							TargetLocations: []*string{
		// 																																								to.Ptr("EastAsia"),
		// 																																								to.Ptr("SoutheastAsia"),
		// 																																								to.Ptr("AustraliaEast"),
		// 																																								to.Ptr("AustraliaSoutheast"),
		// 																																								to.Ptr("BrazilSouth"),
		// 																																								to.Ptr("CanadaCentral"),
		// 																																								to.Ptr("CanadaEast"),
		// 																																								to.Ptr("WestEurope"),
		// 																																								to.Ptr("NorthEurope"),
		// 																																								to.Ptr("CentralIndia"),
		// 																																								to.Ptr("SouthIndia"),
		// 																																								to.Ptr("JapanEast"),
		// 																																								to.Ptr("JapanWest"),
		// 																																								to.Ptr("KoreaCentral"),
		// 																																								to.Ptr("KoreaSouth"),
		// 																																								to.Ptr("UkWest"),
		// 																																								to.Ptr("UkSouth"),
		// 																																								to.Ptr("EastUs"),
		// 																																								to.Ptr("WestUs2"),
		// 																																								to.Ptr("SouthCentralUs"),
		// 																																								to.Ptr("EastUs2"),
		// 																																								to.Ptr("USGovArizona"),
		// 																																								to.Ptr("USGovVirginia")},
		// 																																							},
		// 																																							{
		// 																																								Category: []*string{
		// 																																									to.Ptr("MemoryOptimized")},
		// 																																									FamilyName: to.Ptr("G_series"),
		// 																																									TargetLocations: []*string{
		// 																																										to.Ptr("SoutheastAsia"),
		// 																																										to.Ptr("AustraliaEast"),
		// 																																										to.Ptr("CanadaCentral"),
		// 																																										to.Ptr("CanadaEast"),
		// 																																										to.Ptr("WestEurope"),
		// 																																										to.Ptr("JapanEast"),
		// 																																										to.Ptr("UkSouth"),
		// 																																										to.Ptr("WestUs2"),
		// 																																										to.Ptr("EastUs2"),
		// 																																										to.Ptr("WestUs"),
		// 																																										to.Ptr("GermanyCentral"),
		// 																																										to.Ptr("USGovVirginia")},
		// 																																									},
		// 																																									{
		// 																																										Category: []*string{
		// 																																											to.Ptr("MemoryOptimized"),
		// 																																											to.Ptr("SupportsPremiumStorage")},
		// 																																											FamilyName: to.Ptr("GS_series"),
		// 																																											TargetLocations: []*string{
		// 																																												to.Ptr("SoutheastAsia"),
		// 																																												to.Ptr("AustraliaEast"),
		// 																																												to.Ptr("CanadaCentral"),
		// 																																												to.Ptr("CanadaEast"),
		// 																																												to.Ptr("WestEurope"),
		// 																																												to.Ptr("JapanEast"),
		// 																																												to.Ptr("UkSouth"),
		// 																																												to.Ptr("WestUs2"),
		// 																																												to.Ptr("EastUs2"),
		// 																																												to.Ptr("WestUs"),
		// 																																												to.Ptr("GermanyCentral"),
		// 																																												to.Ptr("USGovVirginia")},
		// 																																											},
		// 																																											{
		// 																																												Category: []*string{
		// 																																													to.Ptr("StorageOptimized"),
		// 																																													to.Ptr("SupportsPremiumStorage")},
		// 																																													FamilyName: to.Ptr("Ls_series"),
		// 																																													TargetLocations: []*string{
		// 																																														to.Ptr("SoutheastAsia"),
		// 																																														to.Ptr("AustraliaEast"),
		// 																																														to.Ptr("CanadaCentral"),
		// 																																														to.Ptr("CanadaEast"),
		// 																																														to.Ptr("WestEurope"),
		// 																																														to.Ptr("JapanEast"),
		// 																																														to.Ptr("UkSouth"),
		// 																																														to.Ptr("WestUs2"),
		// 																																														to.Ptr("EastUs2"),
		// 																																														to.Ptr("WestUs"),
		// 																																														to.Ptr("GermanyCentral"),
		// 																																														to.Ptr("USGovVirginia")},
		// 																																													},
		// 																																													{
		// 																																														Category: []*string{
		// 																																															to.Ptr("HighPerformanceCompute")},
		// 																																															FamilyName: to.Ptr("H_series"),
		// 																																															TargetLocations: []*string{
		// 																																																to.Ptr("SoutheastAsia"),
		// 																																																to.Ptr("AustraliaEast"),
		// 																																																to.Ptr("WestEurope"),
		// 																																																to.Ptr("NorthEurope"),
		// 																																																to.Ptr("CentralIndia"),
		// 																																																to.Ptr("JapanEast"),
		// 																																																to.Ptr("UkSouth"),
		// 																																																to.Ptr("NorthCentralUs"),
		// 																																																to.Ptr("EastUs"),
		// 																																																to.Ptr("WestUs2"),
		// 																																																to.Ptr("SouthCentralUs"),
		// 																																																to.Ptr("WestUs"),
		// 																																																to.Ptr("USGovArizona")},
		// 																																															},
		// 																																															{
		// 																																																Category: []*string{
		// 																																																	to.Ptr("GeneralPurpose"),
		// 																																																	to.Ptr("SupportsPremiumStorage"),
		// 																																																	to.Ptr("Confidential")},
		// 																																																	FamilyName: to.Ptr("DC_Series"),
		// 																																																	TargetLocations: []*string{
		// 																																																		to.Ptr("WestEurope"),
		// 																																																		to.Ptr("EastUs")},
		// 																																																	},
		// 																																																	{
		// 																																																		Category: []*string{
		// 																																																			to.Ptr("HighPerformanceCompute")},
		// 																																																			FamilyName: to.Ptr("Standard_A8_A11"),
		// 																																																			TargetLocations: []*string{
		// 																																																				to.Ptr("WestEurope"),
		// 																																																				to.Ptr("NorthEurope"),
		// 																																																				to.Ptr("NorthCentralUs"),
		// 																																																				to.Ptr("EastUs"),
		// 																																																				to.Ptr("SouthCentralUs"),
		// 																																																				to.Ptr("WestUs")},
		// 																																																		}},
		// 																																																	},
		// 																																															}},
		// 																																														}
	}
}
