
import com.azure.resourcemanager.computeschedule.models.GetOperationStatusRequest;
import java.util.Arrays;

/**
 * Samples for ScheduledActions VirtualMachinesGetOperationStatus.
 */
public final class Main {
    /*
     * x-ms-original-file: 2024-08-15-preview/ScheduledActions_VirtualMachinesGetOperationStatus_MaximumSet_Gen.json
     */
    /**
     * Sample code: ScheduledActions_VirtualMachinesGetOperationStatus - generated by [MinimumSet] rule - generated by
     * [MaximumSet] rule.
     * 
     * @param manager Entry point to ComputeScheduleManager.
     */
    public static void
        scheduledActionsVirtualMachinesGetOperationStatusGeneratedByMinimumSetRuleGeneratedByMaximumSetRule(
            com.azure.resourcemanager.computeschedule.ComputeScheduleManager manager) {
        manager.scheduledActions().virtualMachinesGetOperationStatusWithResponse("htxxasfxaesuecem",
            new GetOperationStatusRequest().withOperationIds(Arrays.asList("01080d2f-1dca-4610-afb4-dd25eec1f3df"))
                .withCorrelationid("01080d2f-1dca-4610-afb4-dd25eec1f3c1"),
            com.azure.core.util.Context.NONE);
    }
}
