
/**
 * Samples for DeidServices List.
 */
public final class Main {
    /*
     * x-ms-original-file:
     * specification/healthdataaiservices/HealthDataAIServices.Management/examples/2024-02-28-preview/
     * DeidServices_ListBySubscription_MaximumSet_Gen.json
     */
    /**
     * Sample code: DeidServices_ListBySubscription - generated by [MaximumSet] rule - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to HealthDataAIServicesManager.
     */
    public static void deidServicesListBySubscriptionGeneratedByMaximumSetRuleGeneratedByMaximumSetRule(
        com.azure.resourcemanager.healthdataaiservices.HealthDataAIServicesManager manager) {
        manager.deidServices().list(com.azure.core.util.Context.NONE);
    }
}
