
/**
 * Samples for DeidServices Delete.
 */
public final class Main {
    /*
     * x-ms-original-file:
     * specification/healthdataaiservices/HealthDataAIServices.Management/examples/2024-02-28-preview/
     * DeidServices_Delete_MaximumSet_Gen.json
     */
    /**
     * Sample code: DeidServices_Delete - generated by [MaximumSet] rule - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to HealthDataAIServicesManager.
     */
    public static void deidServicesDeleteGeneratedByMaximumSetRuleGeneratedByMaximumSetRule(
        com.azure.resourcemanager.healthdataaiservices.HealthDataAIServicesManager manager) {
        manager.deidServices().delete("rgopenapi", "deidTest", com.azure.core.util.Context.NONE);
    }
}
