
/**
 * Samples for Operations List.
 */
public final class Main {
    /*
     * x-ms-original-file:
     * specification/healthdataaiservices/HealthDataAIServices.Management/examples/2024-02-28-preview/
     * Operations_List_MinimumSet_Gen.json
     */
    /**
     * Sample code: Operations_List_MaximumSet - generated by [MaximumSet] rule - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to HealthDataAIServicesManager.
     */
    public static void operationsListMaximumSetGeneratedByMaximumSetRuleGeneratedByMinimumSetRule(
        com.azure.resourcemanager.healthdataaiservices.HealthDataAIServicesManager manager) {
        manager.operations().list(com.azure.core.util.Context.NONE);
    }
}
