
/**
 * Samples for PrivateEndpointConnections ListByDeidService.
 */
public final class Main {
    /*
     * x-ms-original-file:
     * specification/healthdataaiservices/HealthDataAIServices.Management/examples/2024-02-28-preview/
     * PrivateEndpointConnections_ListByDeidService_MaximumSet_Gen.json
     */
    /**
     * Sample code: PrivateEndpointConnections_ListByDeidService - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to HealthDataAIServicesManager.
     */
    public static void privateEndpointConnectionsListByDeidServiceGeneratedByMaximumSetRule(
        com.azure.resourcemanager.healthdataaiservices.HealthDataAIServicesManager manager) {
        manager.privateEndpointConnections().listByDeidService("rgopenapi", "deidTest",
            com.azure.core.util.Context.NONE);
    }
}
