
/**
 * Samples for PrivateLinks ListByDeidService.
 */
public final class Main {
    /*
     * x-ms-original-file:
     * specification/healthdataaiservices/HealthDataAIServices.Management/examples/2024-02-28-preview/
     * PrivateLinks_ListByDeidService_MaximumSet_Gen.json
     */
    /**
     * Sample code: PrivateLinks_ListByDeidService - generated by [MaximumSet] rule - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to HealthDataAIServicesManager.
     */
    public static void privateLinksListByDeidServiceGeneratedByMaximumSetRuleGeneratedByMaximumSetRule(
        com.azure.resourcemanager.healthdataaiservices.HealthDataAIServicesManager manager) {
        manager.privateLinks().listByDeidService("rgopenapi", "deidTest", com.azure.core.util.Context.NONE);
    }
}
