
/**
 * Samples for EnterpriseMccCacheNodesOperations GetCacheNodeInstallDetails.
 */
public final class Main {
    /*
     * x-ms-original-file:
     * 2023-05-01-preview/EnterpriseMccCacheNodesOperations_GetCacheNodeInstallDetails_MaximumSet_Gen.json
     */
    /**
     * Sample code: Gets required properties for enterprise Mcc CacheNode resource install key details - generated by
     * [MaximumSet] rule.
     * 
     * @param manager Entry point to ConnectedCacheManager.
     */
    public static void
        getsRequiredPropertiesForEnterpriseMccCacheNodeResourceInstallKeyDetailsGeneratedByMaximumSetRule(
            com.azure.resourcemanager.connectedcache.ConnectedCacheManager manager) {
        manager.enterpriseMccCacheNodesOperations().getCacheNodeInstallDetailsWithResponse("rgConnectedCache",
            "fzwxcjmdpxxzayecabqqlh", "ccexmqqttritxvtctivraso", com.azure.core.util.Context.NONE);
    }
}
