
/**
 * Samples for IspCacheNodesOperations Get.
 */
public final class Main {
    /*
     * x-ms-original-file: 2023-05-01-preview/IspCacheNodesOperations_Get_MaximumSet_Gen.json
     */
    /**
     * Sample code: IspCacheNodes Get resource - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to ConnectedCacheManager.
     */
    public static void ispCacheNodesGetResourceGeneratedByMaximumSetRule(
        com.azure.resourcemanager.connectedcache.ConnectedCacheManager manager) {
        manager.ispCacheNodesOperations().getWithResponse("rgConnectedCache",
            "sgtqjsitdrskmgyrrkntszwrrjjkretscpjgaezraucvcwececlelcsorfunrnvxyxcsrg", "lbsziwmudcjnwnwy",
            com.azure.core.util.Context.NONE);
    }
}
