
/**
 * Samples for IspCustomers ListByResourceGroup.
 */
public final class Main {
    /*
     * x-ms-original-file: 2023-05-01-preview/IspCustomers_ListByResourceGroup_MaximumSet_Gen.json
     */
    /**
     * Sample code: IspCustomers resource List by Resource group - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to ConnectedCacheManager.
     */
    public static void ispCustomersResourceListByResourceGroupGeneratedByMaximumSetRule(
        com.azure.resourcemanager.connectedcache.ConnectedCacheManager manager) {
        manager.ispCustomers().listByResourceGroup("rgConnectedCache", com.azure.core.util.Context.NONE);
    }
}
