
/**
 * Samples for IspCacheNodesOperations GetCacheNodeInstallDetails.
 */
public final class Main {
    /*
     * x-ms-original-file: 2023-05-01-preview/IspCacheNodesOperations_GetCacheNodeInstallDetails_MaximumSet_Gen.json
     */
    /**
     * Sample code: ispCacheNode resource get install details - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to ConnectedCacheManager.
     */
    public static void ispCacheNodeResourceGetInstallDetailsGeneratedByMaximumSetRule(
        com.azure.resourcemanager.connectedcache.ConnectedCacheManager manager) {
        manager.ispCacheNodesOperations().getCacheNodeInstallDetailsWithResponse("rgConnectedCache", "MccRPTest1",
            "MCCCachenode1", com.azure.core.util.Context.NONE);
    }
}
