
/**
 * Samples for IspCacheNodesOperations Delete.
 */
public final class Main {
    /*
     * x-ms-original-file: 2023-05-01-preview/IspCacheNodesOperations_Delete_MaximumSet_Gen.json
     */
    /**
     * Sample code: IspCacheNodes delete Operation - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to ConnectedCacheManager.
     */
    public static void ispCacheNodesDeleteOperationGeneratedByMaximumSetRule(
        com.azure.resourcemanager.connectedcache.ConnectedCacheManager manager) {
        manager.ispCacheNodesOperations().delete("rgConnectedCache", "lvpcosvbfxtpzscakewx",
            "wsiruvexelltpbouqxvsogqpxdizcwqwfowybncvjunlakjwcpgmqbdbgzjrsmxlkczxnsxfonhnqqa",
            com.azure.core.util.Context.NONE);
    }
}
