
/**
 * Samples for IspCustomers List.
 */
public final class Main {
    /*
     * x-ms-original-file: 2023-05-01-preview/IspCustomers_ListBySubscription_MaximumSet_Gen.json
     */
    /**
     * Sample code: ispCustomer List by Subscription - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to ConnectedCacheManager.
     */
    public static void ispCustomerListBySubscriptionGeneratedByMaximumSetRule(
        com.azure.resourcemanager.connectedcache.ConnectedCacheManager manager) {
        manager.ispCustomers().list(com.azure.core.util.Context.NONE);
    }
}
