
/**
 * Samples for IspCustomers GetByResourceGroup.
 */
public final class Main {
    /*
     * x-ms-original-file: 2023-05-01-preview/IspCustomers_Get_MaximumSet_Gen.json
     */
    /**
     * Sample code: IspCustomers Get - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to ConnectedCacheManager.
     */
    public static void ispCustomersGetGeneratedByMaximumSetRule(
        com.azure.resourcemanager.connectedcache.ConnectedCacheManager manager) {
        manager.ispCustomers().getByResourceGroupWithResponse("rgConnectedCache", "cmcjfueweicolcjkwmsuvcj",
            com.azure.core.util.Context.NONE);
    }
}
