
import java.util.HashMap;
import java.util.Map;

/**
 * Samples for FileSystems CreateOrUpdate.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-04-16/FileSystems_CreateOrUpdate_MinimumSet_Gen.json
     */
    /**
     * Sample code: FileSystems_CreateOrUpdate_MaximumSet_Gen - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to QumuloManager.
     */
    public static void fileSystemsCreateOrUpdateMaximumSetGenGeneratedByMinimumSetRule(
        com.azure.resourcemanager.qumulo.QumuloManager manager) {
        manager.fileSystems().define("qumulo-fs-01").withRegion("ninyfyhmsedp").withExistingResourceGroup("rgQumulo")
            .create();
    }

    // Use "Map.of" if available
    @SuppressWarnings("unchecked")
    private static <T> Map<String, T> mapOf(Object... inputs) {
        Map<String, T> map = new HashMap<>();
        for (int i = 0; i < inputs.length; i += 2) {
            String key = (String) inputs[i];
            T value = (T) inputs[i + 1];
            map.put(key, value);
        }
        return map;
    }
}
