
/**
 * Samples for AutoUpgradeProfiles Delete.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-03-01/AutoUpgradeProfiles_Delete_MaximumSet_Gen.json
     */
    /**
     * Sample code: Delete an AutoUpgradeProfile resource. - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to ContainerServiceFleetManager.
     */
    public static void deleteAnAutoUpgradeProfileResourceGeneratedByMaximumSetRule(
        com.azure.resourcemanager.containerservicefleet.ContainerServiceFleetManager manager) {
        manager.autoUpgradeProfiles().delete("rgfleets", "fleet1", "autoupgradeprofile1", "qmdsmmawj",
            com.azure.core.util.Context.NONE);
    }
}
