
/**
 * Samples for AutoUpgradeProfiles ListByFleet.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-03-01/AutoUpgradeProfiles_ListByFleet_MaximumSet_Gen.json
     */
    /**
     * Sample code: Lists the AutoUpgradeProfile resources by fleet. - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to ContainerServiceFleetManager.
     */
    public static void listsTheAutoUpgradeProfileResourcesByFleetGeneratedByMaximumSetRule(
        com.azure.resourcemanager.containerservicefleet.ContainerServiceFleetManager manager) {
        manager.autoUpgradeProfiles().listByFleet("rgfleets", "fleet1", com.azure.core.util.Context.NONE);
    }
}
