
/**
 * Samples for FleetMembers ListByFleet.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-03-01/FleetMembers_ListByFleet_MaximumSet_Gen.json
     */
    /**
     * Sample code: Lists the members of a Fleet. - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to ContainerServiceFleetManager.
     */
    public static void listsTheMembersOfAFleetGeneratedByMaximumSetRule(
        com.azure.resourcemanager.containerservicefleet.ContainerServiceFleetManager manager) {
        manager.fleetMembers().listByFleet("rgfleets", "fleet1", com.azure.core.util.Context.NONE);
    }
}
