
/**
 * Samples for FleetUpdateStrategies Get.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-03-01/FleetUpdateStrategies_Get_MaximumSet_Gen.json
     */
    /**
     * Sample code: Get a FleetUpdateStrategy resource. - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to ContainerServiceFleetManager.
     */
    public static void getAFleetUpdateStrategyResourceGeneratedByMaximumSetRule(
        com.azure.resourcemanager.containerservicefleet.ContainerServiceFleetManager manager) {
        manager.fleetUpdateStrategies().getWithResponse("rgfleets", "fleet1", "fleet1",
            com.azure.core.util.Context.NONE);
    }
}
