
/**
 * Samples for FleetUpdateStrategies ListByFleet.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-03-01/FleetUpdateStrategies_ListByFleet_MaximumSet_Gen.json
     */
    /**
     * Sample code: List the FleetUpdateStrategy resources by fleet. - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to ContainerServiceFleetManager.
     */
    public static void listTheFleetUpdateStrategyResourcesByFleetGeneratedByMaximumSetRule(
        com.azure.resourcemanager.containerservicefleet.ContainerServiceFleetManager manager) {
        manager.fleetUpdateStrategies().listByFleet("rgfleets", "fleet1", com.azure.core.util.Context.NONE);
    }
}
