
/**
 * Samples for UpdateRuns Get.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-03-01/UpdateRuns_Get_MaximumSet_Gen.json
     */
    /**
     * Sample code: Gets an UpdateRun resource. - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to ContainerServiceFleetManager.
     */
    public static void getsAnUpdateRunResourceGeneratedByMaximumSetRule(
        com.azure.resourcemanager.containerservicefleet.ContainerServiceFleetManager manager) {
        manager.updateRuns().getWithResponse("rgfleets", "fleet1", "fleet1", com.azure.core.util.Context.NONE);
    }
}
