
/**
 * Samples for UnifiedResilienceItems List.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-10-01/UnifiedResilienceItems_List_MinimumSet_Gen.json
     */
    /**
     * Sample code: UnifiedResilienceItems_List_MaximumSet - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to ResilienceManagementManager.
     */
    public static void unifiedResilienceItemsListMaximumSetGeneratedByMinimumSetRule(
        com.azure.resourcemanager.resiliencemanagement.ResilienceManagementManager manager) {
        manager.unifiedResilienceItems().list("sampleServiceGroupName", null, null, com.azure.core.util.Context.NONE);
    }
}
