name: Azure SDK Java Sample Issue
description: Let us know if you have any issue with our Azure SDK for Java sample
title: "[Java Sample Issue]"

body:
  - type: input
    id: library
    attributes:
      label: Library name and version
      description: Name and version of the Library package used
      placeholder: ex. Azure.Storage.Blobs 12.2.0
    validations:
      required: true
  - type: checkboxes
    id: issuetype
    attributes:
      label: Sample Issue Type
      description: Sample Issue Type
      options:
        - label: Sample not working
        - label: Sample missing
        - label: Do not understand sample
    validations:
      required: true
  - type: textarea
    id: background
    attributes:
      label: Issue details
      description: Tell us more about the issue you are having with the sample
      placeholder: Description
    validations:
      required: true 
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: |
        Provide a description of the expected behavior.
      placeholder: Expected behavior
    validations:
      required: false
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: |
        Provide a description of the actual behavior observed. If applicable please include any error messages, exception stacktraces or memory dumps.
      placeholder: Actual behavior
    validations:
      required: false
  - type: textarea
    id: repro-steps
    attributes:
      label: Reproduction Steps
      description: |
        Please include minimal steps to reproduce the problem if possible. E.g.: the smallest possible code snippet; or a small project, with steps to run it. If possible include text as text rather than screenshots (so it shows up in searches).
      placeholder: Minimal Reproduction
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide more information on your environment:
          * JAVA Version
          * OS Version
          * IDE and version
      placeholder: Environment
    validations:
      required: false
