
/**
 * Samples for SitesBySubscription Get.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-03-01-preview/SitesBySubscription_Get_MaximumSet_Gen.json
     */
    /**
     * Sample code: Get Site Subscription - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to SiteManagerManager.
     */
    public static void
        getSiteSubscriptionGeneratedByMaximumSetRule(com.azure.resourcemanager.sitemanager.SiteManagerManager manager) {
        manager.sitesBySubscriptions().getWithResponse("string", com.azure.core.util.Context.NONE);
    }
}
