
/**
 * Samples for SitesBySubscription List.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-03-01-preview/SitesBySubscription_List_MaximumSet_Gen.json
     */
    /**
     * Sample code: List by Subscription - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to SiteManagerManager.
     */
    public static void
        listBySubscriptionGeneratedByMaximumSetRule(com.azure.resourcemanager.sitemanager.SiteManagerManager manager) {
        manager.sitesBySubscriptions().list(com.azure.core.util.Context.NONE);
    }
}
