
/**
 * Samples for SitesByServiceGroup ListByServiceGroup.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-06-01/SitesByServiceGroup_ListByServiceGroup_MaximumSet_Gen.json
     */
    /**
     * Sample code: SitesByServiceGroup_ListByServiceGroup - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to SiteManagerManager.
     */
    public static void sitesByServiceGroupListByServiceGroupGeneratedByMaximumSetRule(
        com.azure.resourcemanager.sitemanager.SiteManagerManager manager) {
        manager.sitesByServiceGroups().listByServiceGroup("string", com.azure.core.util.Context.NONE);
    }
}
