
/**
 * Samples for Sites GetByResourceGroup.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-06-01/Sites_Get_MaximumSet_Gen.json
     */
    /**
     * Sample code: Get Site - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to SiteManagerManager.
     */
    public static void
        getSiteGeneratedByMaximumSetRule(com.azure.resourcemanager.sitemanager.SiteManagerManager manager) {
        manager.sites().getByResourceGroupWithResponse("rgsites", "string", com.azure.core.util.Context.NONE);
    }
}
