
/**
 * Samples for Sites ListByResourceGroup.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-06-01/Sites_ListByResourceGroup_MaximumSet_Gen.json
     */
    /**
     * Sample code: List by Site Subscription - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to SiteManagerManager.
     */
    public static void listBySiteSubscriptionGeneratedByMaximumSetRule(
        com.azure.resourcemanager.sitemanager.SiteManagerManager manager) {
        manager.sites().listByResourceGroup("rgsites", com.azure.core.util.Context.NONE);
    }
}
