
/**
 * Samples for SitesByServiceGroup Delete.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-06-01/SitesByServiceGroup_Delete_MaximumSet_Gen.json
     */
    /**
     * Sample code: SitesByServiceGroup_Delete - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to SiteManagerManager.
     */
    public static void sitesByServiceGroupDeleteGeneratedByMaximumSetRule(
        com.azure.resourcemanager.sitemanager.SiteManagerManager manager) {
        manager.sitesByServiceGroups().deleteByResourceGroupWithResponse("string", "string",
            com.azure.core.util.Context.NONE);
    }
}
