
/**
 * Samples for SitesBySubscription Delete.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-06-01/SitesBySubscription_Delete_MaximumSet_Gen.json
     */
    /**
     * Sample code: Delete Site Subscription - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to SiteManagerManager.
     */
    public static void deleteSiteSubscriptionGeneratedByMaximumSetRule(
        com.azure.resourcemanager.sitemanager.SiteManagerManager manager) {
        manager.sitesBySubscriptions().deleteWithResponse("string", com.azure.core.util.Context.NONE);
    }
}
