
/**
 * Samples for Sites Delete.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-06-01/Sites_Delete_MaximumSet_Gen.json
     */
    /**
     * Sample code: Delete Site - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to SiteManagerManager.
     */
    public static void
        deleteSiteGeneratedByMaximumSetRule(com.azure.resourcemanager.sitemanager.SiteManagerManager manager) {
        manager.sites().deleteByResourceGroupWithResponse("rgsites", "string", com.azure.core.util.Context.NONE);
    }
}
