
/**
 * Samples for Instances GetByResourceGroup.
 */
public final class Main {
    /*
     * x-ms-original-file: 2024-09-18-preview/Instances_Get_MaximumSet_Gen.json
     */
    /**
     * Sample code: Instances_Get - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to WeightsAndBiasesManager.
     */
    public static void instancesGetGeneratedByMaximumSetRule(
        com.azure.resourcemanager.weightsandbiases.WeightsAndBiasesManager manager) {
        manager.instances().getByResourceGroupWithResponse("rgopenapi", "myinstance", com.azure.core.util.Context.NONE);
    }
}
