
/**
 * Samples for Instances ListByResourceGroup.
 */
public final class Main {
    /*
     * x-ms-original-file: 2024-09-18-preview/Instances_ListByResourceGroup_MinimumSet_Gen.json
     */
    /**
     * Sample code: Instances_ListByResourceGroup - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to WeightsAndBiasesManager.
     */
    public static void instancesListByResourceGroupGeneratedByMinimumSetRule(
        com.azure.resourcemanager.weightsandbiases.WeightsAndBiasesManager manager) {
        manager.instances().listByResourceGroup("rgopenapi", com.azure.core.util.Context.NONE);
    }
}
