
/**
 * Samples for CloudAccounts Delete.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-07-03-preview/CloudAccounts_Delete_MaximumSet_Gen.json
     */
    /**
     * Sample code: CloudAccounts_Delete_MaximumSet - generated by [MaximumSet] rule - generated by [MaximumSet] rule -
     * generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to CommvaultContentStoreManager.
     */
    public static void
        cloudAccountsDeleteMaximumSetGeneratedByMaximumSetRuleGeneratedByMaximumSetRuleGeneratedByMaximumSetRule(
            com.azure.resourcemanager.commvaultcontentstore.CommvaultContentStoreManager manager) {
        manager.cloudAccounts().delete("rgcommvault", "sample-cloudAccountName", com.azure.core.util.Context.NONE);
    }
}
