
/**
 * Samples for CloudAccounts LatestLinkedSaaS.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-07-03-preview/CloudAccounts_LatestLinkedSaaS_MaximumSet_Gen.json
     */
    /**
     * Sample code: Returns the latest SaaS linked to the cloud account. - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to CommvaultContentStoreManager.
     */
    public static void returnsTheLatestSaaSLinkedToTheCloudAccountGeneratedByMaximumSetRule(
        com.azure.resourcemanager.commvaultcontentstore.CommvaultContentStoreManager manager) {
        manager.cloudAccounts().latestLinkedSaaSWithResponse("rg-commvault", "contoso-cloud-account",
            com.azure.core.util.Context.NONE);
    }
}
