
/**
 * Samples for CloudAccounts List.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-07-03-preview/CloudAccounts_ListBySubscription_MaximumSet_Gen.json
     */
    /**
     * Sample code: CloudAccounts_ListBySubscription_MaximumSet - generated by [MaximumSet] rule - generated by
     * [MaximumSet] rule - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to CommvaultContentStoreManager.
     */
    public static void
        cloudAccountsListBySubscriptionMaximumSetGeneratedByMaximumSetRuleGeneratedByMaximumSetRuleGeneratedByMaximumSetRule(
            com.azure.resourcemanager.commvaultcontentstore.CommvaultContentStoreManager manager) {
        manager.cloudAccounts().list(com.azure.core.util.Context.NONE);
    }
}
