
/**
 * Samples for Operations List.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-07-03-preview/Operations_List_MaximumSet_Gen.json
     */
    /**
     * Sample code: Operations_List_MaximumSet - generated by [MaximumSet] rule - generated by [MaximumSet] rule -
     * generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to CommvaultContentStoreManager.
     */
    public static void
        operationsListMaximumSetGeneratedByMaximumSetRuleGeneratedByMaximumSetRuleGeneratedByMaximumSetRule(
            com.azure.resourcemanager.commvaultcontentstore.CommvaultContentStoreManager manager) {
        manager.operations().list(com.azure.core.util.Context.NONE);
    }
}
