
/**
 * Samples for Plans ListByCloudAccount.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-07-03-preview/Plans_ListByCloudAccount_MaximumSet_Gen.json
     */
    /**
     * Sample code: Plans_ListByCloudAccount_MaximumSet - generated by [MaximumSet] rule - generated by [MaximumSet]
     * rule - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to CommvaultContentStoreManager.
     */
    public static void
        plansListByCloudAccountMaximumSetGeneratedByMaximumSetRuleGeneratedByMaximumSetRuleGeneratedByMaximumSetRule(
            com.azure.resourcemanager.commvaultcontentstore.CommvaultContentStoreManager manager) {
        manager.plans().listByCloudAccount("rgcommvault", "sample-cloudAccountName", com.azure.core.util.Context.NONE);
    }
}
