
/**
 * Samples for Plans Get.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-07-03-preview/Plans_Get_MaximumSet_Gen.json
     */
    /**
     * Sample code: Plans_Get_MaximumSet - generated by [MaximumSet] rule - generated by [MaximumSet] rule - generated
     * by [MaximumSet] rule.
     * 
     * @param manager Entry point to CommvaultContentStoreManager.
     */
    public static void plansGetMaximumSetGeneratedByMaximumSetRuleGeneratedByMaximumSetRuleGeneratedByMaximumSetRule(
        com.azure.resourcemanager.commvaultcontentstore.CommvaultContentStoreManager manager) {
        manager.plans().getWithResponse("rgcommvault", "sample-cloudAccountName", "sample-planName",
            com.azure.core.util.Context.NONE);
    }
}
