
/**
 * Samples for RoleMappings Delete.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-07-03-preview/RoleMappings_Delete_MaximumSet_Gen.json
     */
    /**
     * Sample code: RoleMappings_Delete_MaximumSet - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to CommvaultContentStoreManager.
     */
    public static void roleMappingsDeleteMaximumSetGeneratedByMaximumSetRule(
        com.azure.resourcemanager.commvaultcontentstore.CommvaultContentStoreManager manager) {
        manager.roleMappings().deleteByResourceGroupWithResponse("rgcommvault", "myCloudAccount",
            com.azure.core.util.Context.NONE);
    }
}
