
import com.azure.resourcemanager.commvaultcontentstore.models.ActivateSaaSParameterRequest;

/**
 * Samples for SaaSOperationGroup ActivateResource.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-07-03-preview/SaaSOperationGroup_ActivateResource_MinimumSet_Gen.json
     */
    /**
     * Sample code: SaaSOperationGroup_ActivateResource_MaximumSet - generated by [MaximumSet] rule - generated by
     * [MinimumSet] rule.
     * 
     * @param manager Entry point to CommvaultContentStoreManager.
     */
    public static void saaSOperationGroupActivateResourceMaximumSetGeneratedByMaximumSetRuleGeneratedByMinimumSetRule(
        com.azure.resourcemanager.commvaultcontentstore.CommvaultContentStoreManager manager) {
        manager.saaSOperationGroups().activateResource(
            new ActivateSaaSParameterRequest().withSaaSGuid("55555555-6666-7777-8888-999999999999"),
            com.azure.core.util.Context.NONE);
    }
}
