
/**
 * Samples for GiVersions ListByLocation.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-03-01/GiVersions_ListByLocation_MinimumSet_Gen.json
     */
    /**
     * Sample code: List GiVersions by location - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to OracleDatabaseManager.
     */
    public static void listGiVersionsByLocationGeneratedByMinimumSetRule(
        com.azure.resourcemanager.oracledatabase.OracleDatabaseManager manager) {
        manager.giVersions().listByLocation("eastus", null, null, com.azure.core.util.Context.NONE);
    }
}
