const { ContainerInstanceManagementClient } = require("@azure/arm-containerinstance");
const { DefaultAzureCredential } = require("@azure/identity");

/**
 * This sample demonstrates how to create or update container groups with specified configurations.
 *
 * @summary create or update container groups with specified configurations.
 * x-ms-original-file: 2026-06-01-preview/ContainerGroupsCreateOrUpdateSecretReference.json
 */
async function containerGroupsCreateOrUpdateSecretReference() {
  const credential = new DefaultAzureCredential();
  const subscriptionId = "00000000-0000-0000-0000-000000000000";
  const client = new ContainerInstanceManagementClient(credential, subscriptionId);
  const result = await client.containerGroups.createOrUpdate("demo", "demo1", {
    identity: {
      type: "UserAssigned",
      userAssignedIdentities: {
        "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myResourceGroup/providers/Microsoft.ManagedIdentity/userAssignedIdentities/identity-name":
          {},
      },
    },
    location: "west us",
    containers: [
      {
        name: "demo1",
        command: [],
        environmentVariables: [{ name: "envSecret", secureValueReference: "envSecretRef" }],
        image: "privateRegistryImage",
        ports: [{ port: 80 }],
        resources: { requests: { cpu: 1, gpu: { count: 1, sku: "K80" }, memoryInGB: 1.5 } },
        volumeMounts: [
          { name: "volume1", mountPath: "/mnt/volume1", readOnly: false },
          { name: "volume2", mountPath: "/mnt/volume2", readOnly: false },
          { name: "volume3", mountPath: "/mnt/volume3", readOnly: true },
        ],
      },
    ],
    diagnostics: {
      logAnalytics: {
        logType: "ContainerInsights",
        metadata: { "test-key": "test-metadata-value" },
        workspaceId: "workspaceid",
        workspaceKey: "workspaceKey",
        workspaceResourceId:
          "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/rg/providers/microsoft.operationalinsights/workspaces/workspace",
      },
    },
    dnsConfig: {
      nameServers: ["1.1.1.1"],
      options: "ndots:2",
      searchDomains: "cluster.local svc.cluster.local",
    },
    imageRegistryCredentials: [
      {
        passwordReference: "privateRegistryKeyRef",
        server: "demoregistry.azurecr.io",
        username: "registryUserName",
      },
    ],
    ipAddress: {
      type: "Public",
      autoGeneratedDomainNameLabelScope: "Unsecure",
      dnsNameLabel: "dnsnamelabel1",
      ports: [{ port: 80, protocol: "TCP" }],
    },
    osType: "Linux",
    secretReferences: [
      {
        name: "envSecretRef",
        identity:
          "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myResourceGroup/providers/Microsoft.ManagedIdentity/userAssignedIdentities/identity-name",
        secretReferenceUri: "https://keyvaultname.vault.azure.net/secrets/envSecret",
      },
      {
        name: "accountKeyRef",
        identity:
          "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myResourceGroup/providers/Microsoft.ManagedIdentity/userAssignedIdentities/identity-name",
        secretReferenceUri: "https://keyvaultname.vault.azure.net/secrets/accountKey",
      },
      {
        name: "volumeSecretRef",
        identity:
          "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myResourceGroup/providers/Microsoft.ManagedIdentity/userAssignedIdentities/identity-name",
        secretReferenceUri: "https://keyvaultname.vault.azure.net/secrets/volumeSecret",
      },
      {
        name: "privateRegistryKeyRef",
        identity:
          "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myResourceGroup/providers/Microsoft.ManagedIdentity/userAssignedIdentities/identity-name",
        secretReferenceUri: "https://keyvaultname.vault.azure.net/secrets/privateRegistryKey",
      },
    ],
    subnetIds: [
      {
        id: "[resourceId('Microsoft.Network/virtualNetworks/subnets', parameters('vnetName'), parameters('subnetName'))]",
      },
    ],
    volumes: [
      {
        name: "volume1",
        azureFile: {
          shareName: "shareName",
          storageAccountKeyReference: "accountKeyRef",
          storageAccountName: "accountName",
        },
      },
      { name: "volume2", emptyDir: {} },
      {
        name: "volume3",
        secret: { secretKey1: "SecretValue1InBase64" },
        secretReference: { secretKey2: "volumeSecretRef" },
      },
    ],
  });
  console.log(result);
}
