
/**
 * Samples for Organizations List.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-06-01/Organizations_ListBySubscription_MinimumSet_Gen.json
     */
    /**
     * Sample code: Organizations_ListBySubscription_MaximumSet - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to MongoDBAtlasManager.
     */
    public static void organizationsListBySubscriptionMaximumSetGeneratedByMinimumSetRule(
        com.azure.resourcemanager.mongodbatlas.MongoDBAtlasManager manager) {
        manager.organizations().list(com.azure.core.util.Context.NONE);
    }
}
