
/**
 * Samples for OperationStatus Get.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-08-01-preview/OperationStatus_Get_MinimumSet_Gen.json
     */
    /**
     * Sample code: OperationStatus_Get_MaximumSet - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to PlatformValidationManager.
     */
    public static void operationStatusGetMaximumSetGeneratedByMinimumSetRule(
        com.azure.resourcemanager.platformvalidation.PlatformValidationManager manager) {
        manager.operationStatus().getWithResponse("southcentralus", "11111111-1111-4111-8111-111111111111",
            com.azure.core.util.Context.NONE);
    }
}
