
/**
 * Samples for ValidationTestVersions List.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-08-01-preview/ValidationTestVersions_List_MaximumSet_Gen.json
     */
    /**
     * Sample code: ValidationTestVersions_List_MaximumSet - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to PlatformValidationManager.
     */
    public static void validationTestVersionsListMaximumSetGeneratedByMaximumSetRule(
        com.azure.resourcemanager.platformvalidation.PlatformValidationManager manager) {
        manager.validationTestVersions().list("linux-quality-validation", "audience eq 'Public'",
            com.azure.core.util.Context.NONE);
    }
}
