
/**
 * Samples for Organizations List.
 */
public final class Main {
    /*
     * x-ms-original-file: specification/liftrastronomer/resource-manager/Astronomer.Astro/stable/2023-08-01/examples/
     * Organizations_ListBySubscription_MaximumSet_Gen.json
     */
    /**
     * Sample code: Organizations_ListBySubscription - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to AstroManager.
     */
    public static void
        organizationsListBySubscriptionGeneratedByMaximumSetRule(com.azure.resourcemanager.astro.AstroManager manager) {
        manager.organizations().list(com.azure.core.util.Context.NONE);
    }
}
