
/**
 * Samples for Executions ListByWorkflowVersion.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-06-01/Executions_ListByWorkflowVersion_MaximumSet_Gen.json
     */
    /**
     * Sample code: Executions_ListByWorkflowVersion_MaximumSet - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to WorkloadOrchestrationManager.
     */
    public static void executionsListByWorkflowVersionMaximumSetGeneratedByMaximumSetRule(
        com.azure.resourcemanager.workloadorchestration.WorkloadOrchestrationManager manager) {
        manager.executions().listByWorkflowVersion("rgconfigurationmanager", "abcde", "abcde", "abcde",
            com.azure.core.util.Context.NONE);
    }
}
