
/**
 * Samples for Operations List.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-12-24-preview/Operations_List_MinimumSet_Gen.json
     */
    /**
     * Sample code: Operations_List_MinimumSet - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to NapsterOmniagentApiManager.
     */
    public static void operationsListMinimumSetGeneratedByMinimumSetRule(
        com.azure.resourcemanager.napsteromniagentapi.NapsterOmniagentApiManager manager) {
        manager.operations().list(com.azure.core.util.Context.NONE);
    }
}
