
/**
 * Samples for Organizations LatestLinkedSaaS.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-12-24-preview/Organizations_LatestLinkedSaaS_MaximumSet_Gen.json
     */
    /**
     * Sample code: Organizations_LatestLinkedSaaS_MaximumSet - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to NapsterOmniagentApiManager.
     */
    public static void organizationsLatestLinkedSaaSMaximumSetGeneratedByMaximumSetRule(
        com.azure.resourcemanager.napsteromniagentapi.NapsterOmniagentApiManager manager) {
        manager.organizations().latestLinkedSaaSWithResponse("rgopenapi", "contosoOrg",
            com.azure.core.util.Context.NONE);
    }
}
