
/**
 * Samples for Organizations ListByResourceGroup.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-12-24-preview/Organizations_ListByResourceGroup_MaximumSet_Gen.json
     */
    /**
     * Sample code: Organizations_ListByResourceGroup_MaximumSet - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to NapsterOmniagentApiManager.
     */
    public static void organizationsListByResourceGroupMaximumSetGeneratedByMaximumSetRule(
        com.azure.resourcemanager.napsteromniagentapi.NapsterOmniagentApiManager manager) {
        manager.organizations().listByResourceGroup("rgopenapi", com.azure.core.util.Context.NONE);
    }
}
