
/**
 * Samples for Organizations List.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-12-24-preview/Organizations_ListBySubscription_MinimumSet_Gen.json
     */
    /**
     * Sample code: Organizations_ListBySubscription_MinimumSet - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to NapsterOmniagentApiManager.
     */
    public static void organizationsListBySubscriptionMinimumSetGeneratedByMinimumSetRule(
        com.azure.resourcemanager.napsteromniagentapi.NapsterOmniagentApiManager manager) {
        manager.organizations().list(com.azure.core.util.Context.NONE);
    }
}
