
/**
 * Samples for Organizations GetByResourceGroup.
 */
public final class Main {
    /*
     * x-ms-original-file: 2025-12-24-preview/Organizations_Get_MaximumSet_Gen.json
     */
    /**
     * Sample code: Organizations_Get_MaximumSet - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to NapsterOmniagentApiManager.
     */
    public static void organizationsGetMaximumSetGeneratedByMaximumSetRule(
        com.azure.resourcemanager.napsteromniagentapi.NapsterOmniagentApiManager manager) {
        manager.organizations().getByResourceGroupWithResponse("rgopenapi", "contosoOrg",
            com.azure.core.util.Context.NONE);
    }
}
