
/**
 * Samples for AkriService ListByInstanceResource.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-03-01/AkriService_ListByInstanceResource_MaximumSet_Gen.json
     */
    /**
     * Sample code: AkriService_ListByInstanceResource_MaximumSet - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to IoTOperationsManager.
     */
    public static void akriServiceListByInstanceResourceMaximumSetGeneratedByMaximumSetRule(
        com.azure.resourcemanager.iotoperations.IoTOperationsManager manager) {
        manager.akriServices().listByInstanceResource("rgiotoperations", "resource-name123",
            com.azure.core.util.Context.NONE);
    }
}
