
/**
 * Samples for AkriService Delete.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-03-01/AkriService_Delete_MaximumSet_Gen.json
     */
    /**
     * Sample code: AkriService_Delete_MaximumSet - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to IoTOperationsManager.
     */
    public static void akriServiceDeleteMaximumSetGeneratedByMaximumSetRule(
        com.azure.resourcemanager.iotoperations.IoTOperationsManager manager) {
        manager.akriServices().delete("rgiotoperations", "resource-name123", "resource-name123",
            com.azure.core.util.Context.NONE);
    }
}
