
/**
 * Samples for Organizations List.
 */
public final class Main {
    /*
     * x-ms-original-file: 2024-02-01-preview/Organizations_ListBySubscription_MinimumSet_Gen.json
     */
    /**
     * Sample code: Organizations_ListBySubscription_MaximumSet_Gen - generated by [MaximumSet] rule - generated by
     * [MaximumSet] rule - generated by [MinimumSet] rule.
     * 
     * @param manager Entry point to LambdaTestHyperExecuteManager.
     */
    public static void
        organizationsListBySubscriptionMaximumSetGenGeneratedByMaximumSetRuleGeneratedByMaximumSetRuleGeneratedByMinimumSetRule(
            com.azure.resourcemanager.lambdatesthyperexecute.LambdaTestHyperExecuteManager manager) {
        manager.organizations().list(com.azure.core.util.Context.NONE);
    }
}
