
/**
 * Samples for HcpOpenShiftVersions Get.
 */
public final class Main {
    /*
     * x-ms-original-file: 2026-09-01-preview/HcpOpenShiftVersions_Get_MaximumSet_Gen.json
     */
    /**
     * Sample code: HcpOpenShiftVersions_Get_MaximumSet - generated by [MaximumSet] rule.
     * 
     * @param manager Entry point to RedHatOpenShiftHostedControlPlanesManager.
     */
    public static void hcpOpenShiftVersionsGetMaximumSetGeneratedByMaximumSetRule(
        com.azure.resourcemanager.redhatopenshifthcp.RedHatOpenShiftHostedControlPlanesManager manager) {
        manager.hcpOpenShiftVersions().getWithResponse("uksouth", "4.18.1", com.azure.core.util.Context.NONE);
    }
}
